### ISSUE TITLE
Scroll viewing for item collection

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#100]
Jess made the fantastic suggestion to scroll through items. @jessvu can you attached a mockup of the scroll viewing method, which as you described would look like the quick question scroll viewing.

**Comment by CourtneyMcClellan** [comment]
Jess's mockup of scrolling items: 
<img width="449" alt="Screen Shot 2021-05-04 at 6 20 00 PM" src="https://user-images.githubusercontent.com/77364108/117078285-96b8c580-ad07-11eb-889e-70350e91c32d.png">

**Comment by adamjarling** [comment]
Just wrapped this and setting a `maxHeight` value on images.  Adjusted for responsive layout as well.

![image](https://user-images.githubusercontent.com/3020266/117582815-7d2dca00-b0c9-11eb-8164-50fff90aebf7.png)
