### ISSUE TITLE
upload new stamps

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#102]
@adamjarling upload additional stamps (there will likely be an editing process but I think it would be helpful to see them all in the tool)

https://drive.google.com/drive/folders/1CAHbf27CrzC93yT9pxas-gG66XcdEm6F?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan Issues also with the new Stamp SVG files.   Looks like the new SVG files are just embedded Images, saved as an SVG file.  The previous SVG files are saved out as Paths, which allows our app to dynamically fill the SVG stamp files with selected colors.  The new Stamp files are not set up to allow color fills.

If you, Olivia or @jessvu want to validate the new files, here's a link to the existing SVG files we're using for Stamps.  You can download any of them to check that new files are set up the same hopefully?

https://github.com/adamjarling/loc-speculative-annotations/tree/main/src/images/stamps

![image](https://user-images.githubusercontent.com/3020266/117661124-97b48180-b163-11eb-91e2-152a453bfac9.png)

![image](https://user-images.githubusercontent.com/3020266/117660785-35f41780-b163-11eb-97e6-695beead026c.png)

![image](https://user-images.githubusercontent.com/3020266/117661033-76ec2c00-b163-11eb-9252-51fe7451a4cd.png)

**Comment by CourtneyMcClellan** [comment]
@adamjarling can you give this file a try?
https://drive.google.com/file/d/1fS6Sg5r4Aei4Fcya-6ZDCxCr6V2B5AGz/view

**Comment by adamjarling** [comment]
Ah, I want it to work so badly!  But unfortunately still not set up to take the color fill.

![image](https://user-images.githubusercontent.com/3020266/117887204-f833e380-b275-11eb-8192-5a748cba54c2.png)

Maybe @jessvu could help out here?  Here's an example of SVG files she prepped which work like the existing stamp SVGs.

![image](https://user-images.githubusercontent.com/3020266/117887353-2d403600-b276-11eb-96f0-a0626a1d4775.png)

**Comment by CourtneyMcClellan** [comment]
Damn, ok! We will ask Jess.

**Comment by CourtneyMcClellan** [comment]
New stamps Olivia shared

**Comment by CourtneyMcClellan** [comment]
@adamjarling First 29 stamps: https://drive.google.com/drive/folders/1Yxt8pJbROIfpoWKKCYode6v7AizBn9dx

**Comment by adamjarling** [comment]
@CourtneyMcClellan If you're happy with these, feel free to close the issue.

**Comment by CourtneyMcClellan** [comment]
@adamjarling final selection of stamps to be uploaded: https://drive.google.com/drive/folders/1lXvZm6WYvzMrM6C4mqzBxxV5grJtQdij?usp=sharing

**Comment by adamjarling** [comment]
All images updated.  If you'd like a different order, let me know.

![image](https://user-images.githubusercontent.com/3020266/119655988-caab7600-bdef-11eb-906e-93233e0fdee0.png)

**Comment by CourtneyMcClellan** [comment]
Looks great, can we close?
