### ISSUE TITLE
Mouse icon and adjusting item when zoomed

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#103]
Courtney and I are both having trouble adjusting the item to navigate to a particular part once it has been zoomed it at any level. 1) when clicking back on the mouse icon from a different tool, it will not allow you to adjust sometimes. Feels like around 30% of the time to me. Maybe 40%.

2)I keep forgetting that i need to go back and click the mouse icon when im using another tool. is it possible to implement a keyboard shortcut for the item where the arrow keys allow you to move around it and bring things into view when zoomed in?

@CourtneyMcClellan did you have anything to add?

**Comment by CourtneyMcClellan** [comment]
I am unable to move the item side to side. This seems to be true zoomed in and at full size. This may be a limitation, but I wanted to check. 

https://user-images.githubusercontent.com/77364108/117205622-de9b2380-adbf-11eb-8666-1a885d064dac.mov

**Comment by adamjarling** [comment]
Revert OSD configs limiting panning for a test

**Comment by adamjarling** [comment]
@CourtneyMcClellan @jaimemears I'll be pushing up changes this morning which loosen up the panning constraints.  Kick the tires on it this weekend and let me know if better or worse?

**Comment by jaimemears** [comment]
Sounds great! We’ll give it a spin!

**Comment by CourtneyMcClellan** [comment]
Seems like this is working, can we close the issue?

**Comment by adamjarling** [comment]
@CourtneyMcClellan For sure.  If you're happy with the current status, then yes please go ahead and close this issue.
