### ISSUE TITLE
Sun icon for light mode looks like "settings" gear

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#109]
Is there a less confusing icon option? @adamjarling could you put the link in here to the correct Fabric Js library for @jessvu ?

**Comment by adamjarling** [comment]
@jaimemears @jessvu Sure.  The icons are the default dark/light mode icons provided our UI framework ( https://chakra-ui.com/ ), but if you'd like to change either, we can do that.   The link to the more extensive icon package we're using is:

https://react-icons.github.io/react-icons/search

**Comment by CourtneyMcClellan** [comment]
let's go with this one: [image: Screen Shot 2021-05-10 at 10.29.18 PM.png]

**Comment by adamjarling** [comment]
@CourtneyMcClellan Can you re-try the screen shot, or better yet let me know the name of the icon you'd like to use?

**Comment by CourtneyMcClellan** [comment]
ImSun
, [image: Screen Shot 2021-05-13 at 9.42.11 AM.png]

**Comment by adamjarling** [comment]
Got it.  Updated.

![image](https://user-images.githubusercontent.com/3020266/118138415-e6fceb00-b3cb-11eb-9611-d4cbe483a536.png)
