### ISSUE TITLE
Retain dimensions of text box when adjusting size

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#112]
The text can get weirdly stretched right now when the box is being manipulated. is there a way to set the ratio of the box and only alllow for diagnal manipulation to make it bigger or smaller?

**Comment by adamjarling** [comment]
@jaimemears See this issue for details on the status/description/limitations of current implementation.  

https://github.com/adamjarling/loc-speculative-annotations/issues/66

**Comment by jaimemears** [comment]
development entering final sprint - closing this ticket as not a priority for mvp.
