### ISSUE TITLE
Default color for stamp menu

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#114]
Dark blue for light mode. @jessvu what color do you think for dark mode? Can you assign to @CourtneyMcClellan afterwards?

**Comment by CourtneyMcClellan** [comment]
I would think the light purple since we are using the blue for the quick question stamps

**Comment by jessvu** [comment]
<img width="600" alt="Screen Shot 2021-05-09 at 8 52 38 PM" src="https://user-images.githubusercontent.com/32075716/117593032-c6e9d500-b108-11eb-8129-54fb4e41e10e.png">
<img width="600" alt="Screen Shot 2021-05-09 at 8 52 09 PM" src="https://user-images.githubusercontent.com/32075716/117593034-c6e9d500-b108-11eb-897f-a04ab2d3ab79.png">

Here is an example of the default color for the stroke weights, but it should apply to the stamps as well:

Light Mode (unselected): #3E495B, 87% opacity
Light Mode (selected): #3E495B, 100% opacity w/ #EAF1FF hover/background
Dark Mode (unselected): #FFFFFF, 87% opacity
Dark Mode (selected): #FFFFFF, 100% opacity w/  #0F161E hover/background

@CourtneyMcClellan all of this information is available in the Figma file that I shared with Adam as well: https://www.figma.com/file/laNqMbfi7FSeHweqgyH8Jn/Speculative-Annotation-Style-Guide?node-id=1%3A3

**Comment by jaimemears** [comment]
development entering final sprint - closing this ticket as not a priority for mvp.
