### ISSUE TITLE
Stamp tool allows one placement, not on every click

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#115]
Most users will only want to place a stamp once and then click out of it. Right now the user flow is that when the stamp tool is selected, each click places a stamp. Can we set it so that stamp tool gets selected, it places a stamp on the canvas where the user clicks, and then that its?

**Comment by CourtneyMcClellan** [comment]
@adamjarling can we close this?

**Comment by adamjarling** [comment]
@CourtneyMcClellan I haven't implemented this yet.  Do you not want this feature?

**Comment by CourtneyMcClellan** [comment]
Let's keep this open, I'll move it to the to do
. This video shows the difficulties with the 2 click method. It starts with the highlighter tool issue, but then moves to the stamp issue. https://mail.google.com/mail/u/0/#search/grahamo%40umich.edu/FMfcgxwLtstHMQRCpKmGldvbvnhXtTlg?projector=1

**Comment by jaimemears** [comment]
not priority for mvp. closing
