### ISSUE TITLE
Cursor icon lag

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#116]
Currently the cursor icon between the marker and highlighter are visually distinct which is great. But, the icon itself doesnt change when the tool is selected, it only changes if the user selects a different weight for the tool. We are guessing this is a bug? @CourtneyMcClellan could you ask Olivia to share a quick video of this?

**Comment by CourtneyMcClellan** [comment]
Video explaining issue: https://drive.google.com/file/d/1l9NFHhlI-cY_RiiVUKTIIR12FoWxACKh/view?usp=sharing

**Comment by jaimemears** [comment]
development entering final sprint - closing this ticket as not a priority for mvp.
