### ISSUE TITLE
Stamps moving around- too sensitive

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#117]
The stamps  sometimes move around/stretch once placed on the canvas even when user is not holding mouse down.  @CourtneyMcClellan  could Olivia make a video of this for adam?

**Comment by CourtneyMcClellan** [comment]
Video showing issue starts at 40 sec: https://drive.google.com/file/d/1l9NFHhlI-cY_RiiVUKTIIR12FoWxACKh/view

**Comment by adamjarling** [comment]
Yea, this is a timing issue previously noted in event delegation.  The `mouseup` event gets fired too late, and then the stamp draw size state doesn't get cut off.  

There's another issue (https://github.com/adamjarling/loc-speculative-annotations/issues/115) which might fix this.  I'll give that a shot and we'll see?

**Comment by CourtneyMcClellan** [comment]
Sounds good

**Comment by jaimemears** [comment]
We closed 115, gonna close this one too.
