### ISSUE TITLE
Pop up warning when selecting new item

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#121]
"You will lose your current annotations when you select a new item. Continue?"

This message should pop up when a user opens the item gallery. They should have the option of selecting "continue" or "cancel"

**Comment by jaimemears** [comment]
Jaime will update this based on whether we will have a saving affordance or not. If we have the ability to save, the pop up will prompt a saving action. If we dont, then it will be a "continue" or "cancel button.

**Comment by jaimemears** [comment]
Assigning to @CourtneyMcClellan because we need to make a call about pursuing saving or not, and this ticket is dependent on that decision.

**Comment by adamjarling** [comment]
Closing this issue.  

![image](https://user-images.githubusercontent.com/3020266/118570986-cc67a080-b742-11eb-895e-2a9f6cc7c6cf.png)

**Comment by CourtneyMcClellan** [comment]
@jaimemears confirming change of text:

Do you want to save first?

**Comment by jaimemears** [comment]
Yes @adamjarling the text needs to be a lower reading level - Replace all with “Do you want to save first?”

**Comment by adamjarling** [comment]
Updated.

![image](https://user-images.githubusercontent.com/3020266/118824606-9b40ba80-b87f-11eb-99a2-0745878b4e2e.png)

**Comment by adamjarling** [comment]
I'll let either @CourtneyMcClellan or @jaimemears confirm this is the right text in the right place before closing.

**Comment by jaimemears** [comment]
This is correct, thank you. Closing now.
