### ISSUE TITLE
Switching LOC Work warning modal about unsaved work

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#122]
When a user selects a new LOC Work, they should get a warning that their current annotations will be lost if they don't save.  @jaimemears Maybe this is somewhat related to "saving" current user annotations?

![image](https://user-images.githubusercontent.com/3020266/117965771-c3ad3f80-b2e8-11eb-8172-0d5054b0b2b6.png)

**Comment by jaimemears** [comment]
How does this relate to the #121 ticket I made?

If users dont save (if that affordance exists) or download their annotation before selecting a new image, they will lose their work. I see it as related, but not dependent whether a user can save or not.

**Comment by adamjarling** [comment]
Ooops, yea duplicate tickets I suppose.  Feel free to refine and close whichever issue you want.  I think they both cover similar territory.

**Comment by jaimemears** [comment]
ok. am closing this one, refining #121 and moving to needs feedback since its wrapped in this bigger saving question.
