### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#129]
I have had some issues with zooming in the last couple of days, some of which have resolved and some have not: 

- I have found items that were already zoomed in on, or times when panning is difficult. I will test this again now, and note specific issues. 

Image pulling in when trying to view zoomed in annotation- this might be a bug https://drive.google.com/file/d/1bu6DuBTOsfkVsYmIRaHuUXVFRbwn8SZh/view?usp=sharing

Sometimes zoom seems to get tired. After opening and closing several items and panning, zooming with + and - the tool seems to get tired. In testing the collection, it worked well for items 1-12, and then the panning and zooming stops working at item 13 and after.

**Comment by adamjarling** [comment]
I'm not able to re-create this for item 13, but sounds to me like it could be either the browser's memory getting overloaded trying to process a lot of FabricJS canvas elements moving around.  Or it could be a failing network request for an LOC item that's jamming things up.  I'll see if there's anything i can adjust further.

**Comment by CourtneyMcClellan** [comment]
Ok, I have a feeling it is the memory being overloaded.  After opening 4-5
items, if I refresh it is fine again.

**Comment by adamjarling** [comment]
Ok, that info helps.  I'll look into Fabric JS's caching possibilities to maybe take some of the weight off the browser.

**Comment by jaimemears** [comment]
Courtney thinks this looks good can we close @adamjarling ?

**Comment by CourtneyMcClellan** [comment]
@adamjarling @jaimemears actually I do have a concern. I am struggling with the zoom out, zoom in is working well. Not sure if there is anything to be done but I thought I would note

**Comment by adamjarling** [comment]
Running some Performance Diagnostics in Chrome Dev Tools, I'm not seeing anything which immediately jumps out.   

- @CourtneyMcClellan are you seeing with with many Fabric JS annotations while zooming?   
- Do you experience this with no annotations on the canvas?

**Comment by CourtneyMcClellan** [comment]
On Chome I run into zooming issues after opening and closing 4-5 images
with no annotations on them. Zoom stops working at that point. If I reload
the page, then it works again.
