### ISSUE TITLE
Stamp

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#13]
Add support for a generic "Stamp" user tool.  For the prototype, can experiment with these PNG and SVG files.

### Sample files:

![loc-logo-horizantal](https://user-images.githubusercontent.com/3020266/103000974-b63a1900-44f1-11eb-83e6-52b3dee96867.png)

### SVG files to test

- https://github.com/adamjarling/loc-speculative-annotations/blob/main/src/images/faux-art.svg
- https://github.com/adamjarling/loc-speculative-annotations/blob/main/src/images/social-media-logos-Labs.svg

**Comment by CourtneyMcClellan** [comment]
To add to stamps, I would like to add these quick questions found here: 
Quick Questions:

Who
What?
When?
Where?
Why?
How?

What do you see?
What do you think about that?
What does it make you wonder?

What’s going on?
What made you say that?

What do you think happened right before this?
What do you think happened right after this?

[Quick Questions.pdf](https://github.com/adamjarling/loc-speculative-annotations/files/5822400/Quick.Questions.pdf)



They are grouped in the same format see here. These would exist as stamps that could be selected and added to the item like a stamp-- with preselected typeface.

**Comment by adamjarling** [comment]
@CourtneyMcClellan Can you double check the link above?  I can't seem to access it.

**Comment by adamjarling** [comment]
Continuing the work here:

https://github.com/adamjarling/loc-speculative-annotations/issues/23

**Comment by CourtneyMcClellan** [comment]
Olivia is currently working on these quick questions as stamp designs.  They aren't ready but I will notify you when they are.
