### ISSUE TITLE
Navigating between app pages error handling

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#130]
When the user navigates from the Annotations page (with current annotations), to the About or Teach page, their annotations should either get saved and re-displayed when they return (behind the scenes), or they should be warned that their annotations will be lost if they navigate away from the Annotations page (easier solution probably).

Also there's a bug use has a tool selected (say the draw brush tool), then navigates to the About page, then comes back to the Annotations page, the current tool is inactive until they select a new tool.  I think the solution for this is to reset to the Pointer tool whenever a user comes into the Annotations page.

**Comment by adamjarling** [comment]
@jaimemears @CourtneyMcClellan (whenever you have a chance this week, mind running this through the paces, going from About, Teach pages, back into the app...as you would imagine a real world user would use the app?   I updated the navbar to try and catch any unsaved work a user has when navigating from the Canvas part of the app, to the About or Teach page, then back again.  I think it's fairly smooth, but I'm seeing through developer eyes and not user eyes.

**Comment by jaimemears** [comment]
we will look at this 6/2 and reply with any issues spotted

**Comment by CourtneyMcClellan** [comment]
@adamjarling question for this: Would it be possible when someone is on the About or Teach page and clicks annotate (to return to the tool) not to get the pop up "Welcome to Speculative Annotation" again? It seems redundant.
