### ISSUE TITLE
Design update bundle -final (could it be?)

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#131]
Below are the updates to the design of the app. Please see figma and png files attached for more info. The updates begin at "noon" and go clockwise around the app layout.

Update button labels to read "save" and "download" with corresponding icons
add "hide annotation" button
replace zoom "100" with magnifying glass icon
replace logo with updated version including hashtag
update sizing of "i/info" icon and add "learn more"
create top and bottom margins on the canvas (if possible)
move disclaimer onto canvas so that it appears in the downloaded png
delete "change display: my annotation". replace with"staff annotation" pop out button
turn on trashcan functionality
delete top left SA logo
replace "Back to loc.gov" with "Visit loc.gov"
delete name tag

**Comment by jaimemears** [comment]
@jessvu could you add sigma file, the code for the magnifying glass icon, the update logo with hashtag and then assing to Adam?

**Comment by jaimemears** [comment]
<img width="1152" alt="Zoom - v2" src="https://user-images.githubusercontent.com/22895272/118989483-12de1a80-b950-11eb-8bd6-b1320e6593f2.png">

**Comment by jessvu** [comment]
Here is the figma file: https://www.figma.com/file/a8ZSCH7yaVxnrattj7JQVx/New-SA-Layout---May-2020

I added about 10 annotations that you'll see when you click the comment button in the top left.

**Comment by jaimemears** [comment]
Could we prioritize the parts of this on the actual canvas? If some of these get updated then we might be able to catch some of the staff annotations before they are made next week.

**Comment by adamjarling** [comment]
These updates look great and will get them in place tonight.

**Comment by adamjarling** [comment]
These are now in place for Desktop...need to iron out mobile/tablet display next.

**Comment by CourtneyMcClellan** [comment]
@adamjarling I am noticing that the save button looks a little different here. Because it is white, it does not show up in light mode. Additionally, it is sitting in the middle of the top tool bar in the About and Teach pages. Instead of the white button could it look like the above layout?
Please let me know if you had different thinking/strategy 

<img width="1440" alt="Screen Shot 2021-05-25 at 3 11 19 PM" src="https://user-images.githubusercontent.com/77364108/119555354-c473b600-bd6b-11eb-82ea-d3ed0be9d022.png">
<img width="1433" alt="Screen Shot 2021-05-25 at 3 11 27 PM" src="https://user-images.githubusercontent.com/77364108/119555363-c63d7980-bd6b-11eb-9ca1-e5fe4ba684c6.png">

**Comment by adamjarling** [comment]
Hey @CourtneyMcClellan Yea, making the adjustments now:
- Light Mode the My Saved Annotations will be gray like in the mockup
- When on About or Teach, the My Saved Annotations button no longer will appear.

**Comment by adamjarling** [comment]
Latest round of changes includes updates to the "Adjustment Bar" for iPad so all the controls fit into the menu bar.  And also on mobile, the hamburger dropdown menu is now in place.   Let me know if there's additional items to clean up here?

![image](https://user-images.githubusercontent.com/3020266/119986862-fcf0db00-bf89-11eb-92b9-5b3c8bc4555e.png)

![image](https://user-images.githubusercontent.com/3020266/119986974-1db93080-bf8a-11eb-8fd4-29da4bc0e551.png)

**Comment by jessvu** [comment]
Hi Adam, this looks great! Could you just change the hamburger icon to the ellipsis icon. The hamburger makes it look more like navigation menu rather than tools menu. 

![](https://cdn0.iconfinder.com/data/icons/user-interface-255/100/more-512.png)

**Comment by jaimemears** [comment]
Ive been using this on an ipad all day and its great!

**Comment by CourtneyMcClellan** [comment]
It looks great, can we close this?
