### ISSUE TITLE
Metadata panel testing

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#133]
See rows 7 and 8 of the metadata panel spreadsheet for testing. Column G "Questions" and Column L "Research" are the custom fields.
https://docs.google.com/spreadsheets/d/1vlxeZmxp_1KfUlLMvb90AtZ41gDs4iru89JJFAL1H4g/edit#gid=688250769

Row 7 has an item-level record on loc.gov but also some custom info 
Row 8 has only a collection-level record with custom info.

So -
1- How can I format this spreadsheet best for ingest? I am also happy to add custom info to the json files myself if you'd like.
2- Is it possible to update field titles? For example "LOC Image" should be "See item on loc.gov" if possible. All suggested titles I have added as a backspace.

**Comment by adamjarling** [comment]
@jaimemears Currently the Metadata header text is hardcoded into the app in the Metadata component:

`src/components/Metadata/Metadata.js`

I can update these headers now, and I think I get it.  ie. "Contributors" becomes "By".  "Contact" becomes "Ask a Librarian", etc.?

**Comment by jaimemears** [comment]
thats correct.

Sent from my iPad

On May 26, 2021, at 8:31 AM, Adam J. Arling ***@***.***> wrote:

﻿

@jaimemears<https://github.com/jaimemears> Currently the Metadata header text is hardcoded into the app in the Metadata component:

src/components/Metadata/Metadata.js

I can update these headers now, and I think I get it. ie. "Contributors" becomes "By". "Contact" becomes "Ask a Librarian", etc.?

**Comment by adamjarling** [comment]
And yes, the metadata is pulling from LOC manifests, and local IIIF manifests located in this file:

`public/iiif/speculative-annotations-manifest.json`

That's where Questions would live, and if you want to add **Research**, it should live here too.

**Comment by adamjarling** [comment]
Would "Research" be all URL links?   I could try setting this up for a few items so you could see a pattern of how it'd be applied to the manifest file.   Then now and/or into the future you could update the `public/iiif/speculative-annotations-manifest.json` file directly in Github, do a Pull Request (to make sure no code collisions happen), and then the app will automatically pull through the content after the code is merged and the next app build happens.

**Comment by jaimemears** [comment]
Ok. Lmk what i need to do - how to structure the spreadsheet or hand code it in to the manifest- I’m working on this today

Sent from my iPad

On May 26, 2021, at 8:36 AM, Adam J. Arling ***@***.***> wrote:

﻿

And yes, the metadata is pulling from LOC manifests, and local IIIF manifests located in this file:

public/iiif/speculative-annotations-manifest.json

That's where Questions would live, and if you want to add Research, it should live here too.

**Comment by jaimemears** [comment]
OMG YASSSS

Yes, it will always be URL links

Sent from my iPad

On May 26, 2021, at 8:42 AM, Adam J. Arling ***@***.***> wrote:

﻿

Would "Research" be all URL links? I could try setting this up for a few items so you could see a pattern of how it'd be applied to the manifest file. Then now and/or into the future you could update the public/iiif/speculative-annotations-manifest.json file directly in Github, do a Pull Request (to make sure no code collisions happen), and then the app will automatically pull through the content after the code is merged and the next app build happens.

**Comment by adamjarling** [comment]
@jaimemears Feel free to close this if the scope is captured in other issues (I believe)?

**Comment by jaimemears** [comment]
This is covered. Closing.
