### ISSUE TITLE
Text font box hide

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#134]
Low priority-

Possible for format options box to go away once user places text box? it eats up a lot of annotation real estate.

![image](https://user-images.githubusercontent.com/22895272/119570237-d78f8180-bd7d-11eb-998b-979671ffb798.png)

**Comment by adamjarling** [comment]
@jaimemears I just updated the size and layout of the Type Text options panel, reducing its overall size by probably 30%. 

![image](https://user-images.githubusercontent.com/3020266/120107368-71f91780-c126-11eb-8de4-80683c4d5d69.png)

**Comment by adamjarling** [comment]
Also updating the action here to show/hide the Type tool font options when either:

- Beginning to type on canvas
- Clicking on the Type tool button (will toggle)

Let me know if this is what you had in mind?

**Comment by jaimemears** [comment]
This is great, closing issue.
