### ISSUE TITLE
Create hint for "escape" key shortcut

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#135]
users dont know that "escape" is how to make the text box size responsive. Is there a way we could add a hint or something? If not, we will add some tips on the about page.

**Comment by adamjarling** [comment]
@jaimemears Pushing up an update now which looks like this:   The notification won't fire every time you create a new text annotation, but once for each time you load the app in the browser (ie. a page refresh will cause the notification to appear again when creating a new text object).

![image](https://user-images.githubusercontent.com/3020266/121186352-9e025000-c82c-11eb-8ae6-1592d3455778.png)

**Comment by jaimemears** [comment]
That looks great. thanks @adamjarling . I will close this issue.
