### ISSUE TITLE
"Placeholder for generic collection" language in metadata panle

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#146]
For items that read “placeholder for generic collection” - can we change that language? Maybe “back to loc.gov” since that’s what its doing? Ex- Muybridge, Warren, Pueblo, Barton, Mitchell, Anthony

**Comment by adamjarling** [comment]
@jaimemears Currently if a Work has "Generic Collection" in its manifest, it doesn't pull through any Collection info to the Metadata Info panel in the UI.   Would you like to change this so that it displays  "Collection" metadata for every Work, and defaults to "back to loc.gov" for the 5 current Works which now have "Generic Collection"?

**Comment by jaimemears** [comment]
Yes thats correct! Thank you

Sent from my iPad

On Jun 3, 2021, at 8:43 AM, Adam J. Arling ***@***.***> wrote:

﻿

@jaimemears<https://github.com/jaimemears> Currently if a Work has "Generic Collection" in its manifest, it doesn't pull through any Collection info to the Metadata Info panel in the UI. Would you like to change this so that it displays "Collection" metadata for every Work, and defaults to "back to loc.gov" for the 5 current Works which now have "Generic Collection"?

**Comment by adamjarling** [comment]
@jaimemears Updating this now.  So this will cue off the following property in each Manifest work object:

```
"partOf": [
        {
          "id": "iiif/collection-generic/info.json",
          "type": "Collection"
        }
      ],
```

In our app, if you follow the path to `iiif/collection-generic/info.json`, you'll see the text and url values which you can update in the future if you wish.

![image](https://user-images.githubusercontent.com/3020266/120891311-7e212100-c5cd-11eb-829c-8411ad9ef721.png)
