### ISSUE TITLE
Mink letter UID update: Item 2011660380 to be replaced with mm2003084957

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#154]
We got curaotr feedback that we are pulling from the photograph only collection of Mink, not the papers. I checked and this manifest exists. https://www.loc.gov/item/mm2003084957/

I will update the "context" ID in the PR Im doing today but could you update the other dependency files? There is a staff annotation for this item.

**Comment by adamjarling** [comment]
This was added via this commit:

https://github.com/adamjarling/loc-speculative-annotations/commit/bdae4bd20aede2369d90a4bb39b443a299455f2b
