### ISSUE TITLE
update Brown v Board curator annotation

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#161]
This curator annotation needs to be updated: https://drive.google.com/file/d/1xdJRG5ARRVQUptHgA0GNLRSXnhQzYkak/view?usp=sharing

**Comment by adamjarling** [comment]
This got pushed through with yesterdays updates I believe.

**Comment by CourtneyMcClellan** [comment]
There was a spelling error that I wasn't seeing fixed. Could you update it
with this version?

**Comment by adamjarling** [comment]
Ah, yea will do.

**Comment by adamjarling** [comment]
@CourtneyMcClellan @jaimemears Looks like the id for this image (in curator link above) is mal.0773800 instead of mm82052258 (as noted in the curator filename above).

![image](https://user-images.githubusercontent.com/3020266/121536973-2289d580-c9c9-11eb-8cea-5cc77c0d36ac.png)

**Comment by adamjarling** [comment]
Maybe I spoke too soon.  Here's the image we have for mm82052258

![image](https://user-images.githubusercontent.com/3020266/121538044-15211b00-c9ca-11eb-9923-a286c8a031f6.png)

So maybe the curator image in this issue above @CourtneyMcClellan should be for id mal.0773800 ?

**Comment by CourtneyMcClellan** [comment]
- mm82052258 (Earl Warren papers) should be removed

**Comment by adamjarling** [comment]
@CourtneyMcClellan Should mm82052258 should be removed entirely?   Or should I just rename your curator image to have the id mal.0773800?

**Comment by CourtneyMcClellan** [comment]
Wait, I want to make sure I understand. Both images should say, it seems
that one of the items is misnamed. Is that correct?

**Comment by adamjarling** [comment]
I think what solves this is renaming your file at the top in Google Drive (mm82052258_Cannon(2).png) to mal.0773800_Cannon.png.  You can verify ids by clicking on an item in the app, then looking at the URL and seeing what the id is in the URL bar.

**Comment by adamjarling** [comment]
I'm guessing we keep the Work mm82052258, so there remains 40 total in the app.

**Comment by CourtneyMcClellan** [comment]
Yes, that is correct. Great, renamed curator annotation:
https://drive.google.com/drive/folders/1x-m0IJ1RtQ_vyHznxxyRljBFIgP40__8

**Comment by CourtneyMcClellan** [comment]
@adamjarling Checking on this, the curator annotation still needs to be updated but I am hoping my naming error has been resolved. 

https://drive.google.com/drive/folders/1x-m0IJ1RtQ_vyHznxxyRljBFIgP40__8

**Comment by adamjarling** [comment]
Updating now.  Looks good to me.
