### ISSUE TITLE
move 48038600 to the opening page (making it item 1)

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#167]
This item moved to Item 1, and on the opening annotate page

<img width="554" alt="Screen Shot 2021-06-11 at 10 11 25 PM" src="https://user-images.githubusercontent.com/77364108/121762125-ff167600-cb01-11eb-9be8-da0d8a3c4616.png">

**Comment by adamjarling** [comment]
Done.
