### ISSUE TITLE
Set up application wireframing

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#18]
Based on the new wireframes, create a structure for the main application to fit into the wireframe design.

https://ninjamock.com/s/QJ74DHx

**Comment by CourtneyMcClellan** [comment]
On the About Page, Jaime and I have discussed adding a layout similar to the thumbnail page here. The thumbnails would include examples of annotation found in the LOC collection. The images would not need to be able to be pulled into the tool, but instead should clicked on and viewed larger so they can see the annotation. 

Let me know if there are additional questions. If you want me to create a separate issue for this, I am happy to do so. 

<img width="579" alt="Screen Shot 2021-01-15 at 2 15 14 PM" src="https://user-images.githubusercontent.com/77364108/104768720-1c563c80-573c-11eb-9ea5-aba4b9911b3a.png">

**Comment by adamjarling** [comment]
@CourtneyMcClellan Yes, this sounds like a perfect scenario to create a new issue.  For me, it's great to have issues as scoped and specific as possible.  Please do.

**Comment by CourtneyMcClellan** [comment]
Got it! Will do
