### ISSUE TITLE
Delete All

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#19]
Im wondering what the use case is for this. Do the annotations all get cleared anyway when I leave the website or are they stored on my browser so that when i return they are still there?

Is it more likely that I would want to delete select annotation versions then delete all?

### Done looks like
- [ ] Validate we need "Delete All"
- [x] User can delete a selected canvas object

**Comment by adamjarling** [comment]
@jaimemears Yea, I hear ya.  The text could be better, but "Delete All", currently deletes all "saved" canvases a user has stored in their browser (which persist indefinitely until the user clears the browser's cache or `localStorage` state).   A user can save multiple canvas 'sessions' which will appear in the "My Annotations" menu control.

![image](https://user-images.githubusercontent.com/3020266/104519683-741b6900-55bf-11eb-97b7-ace1acf15fc3.png)


This brush control clears all current annotations a user has on the existing screen.  We do need a control to remove an individual annotation if it's selected, and I'll build this out next.

![image](https://user-images.githubusercontent.com/3020266/104519423-03744c80-55bf-11eb-8750-8de97593b7ed.png)

**Comment by adamjarling** [comment]
@jaimemears We can now remove an individual object annotation from the Fabric canvas.  Not sure the best place for this button, but can move it around wherever makes sense.

![image](https://user-images.githubusercontent.com/3020266/104844808-e5953900-5897-11eb-84be-b7c6253e3fcb.png)

**Comment by adamjarling** [comment]
This was fixed at some point as part of UX review.  Currently looks like below screenshot.  Closing.

![image](https://user-images.githubusercontent.com/3020266/110246191-3b976c00-7f2c-11eb-9466-c56cb5df1a02.png)

**Comment by jaimemears** [comment]
Awesome! Thanks Adam.
