### ISSUE TITLE
"Projector" style overlay

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#20]
Design and perhaps functionality to visually communicate that there's a transparent overlay over the LC item. Courtney recommended two pieces of tape at the corners of the image, Jaime suggested a slight "tint" to the image to communicate an overlay. Courtney, could you attach some drawings?

**Comment by jessvu** [comment]
![image](https://user-images.githubusercontent.com/32075716/104673043-f6368b00-56ae-11eb-9382-5b91d206ae34.png)

Here's a mockup of what I had in mind for the overlay. It's similar to Jaime's with the tint overlay. I am imagining that the feature can function like layers do in the Adobe programs and other similar drawing applications. Users can turn off and on each layer with the User's layer being editable and the Curator's a static image. This functionality would allow the users to have both layers turned on at the same time or one at a time.

**Comment by CourtneyMcClellan** [comment]
Yes, I will make a little sketch and post soon

**Comment by adamjarling** [comment]
Thinking through this as a developer, here's how the Application layers are currently set up...this will help us figure out how to achieve this feature.

### Application layers
#### Bottom layer
OpenSeadragon canvas which contains the source image

#### Middle layer
Fabric JS canvas which holds all user annotations

#### Top layer
User created objects on the Fabric JS canvas

------------------------------
If we want to pin the overlay to the source image, then we'll need to either add it to the OSD layer, or to the Fabric layer as a non-editable Fabric object, sent to the very bottom of the Fabric object stack.

I'll have to think about how we could toggle these layers on/off.   Where in the UI would this Layers selection control live, and what would it look like?

**Comment by jaimemears** [comment]
Yes, I was imagining this would be on the Fabric JS layer. The design elements of this overlay would be consistent for the “My annotation“ experience regardless of image.

For layer selection - When toggling to the “Curator Annotation” view in the UI, some of these design elements would be different, if possible, such as the color of the border, or perhaps a permanent graphic akin to the masking tape, in order to signal to the user that you were in the “Curator Annotation” space.

Do you need pngs of the tape illustration to prototype this?

**Comment by CourtneyMcClellan** [comment]
https://slack-files.com/T01FY6ZS1MM-F01JXBMDCAF-1e5e8b5aab

Link to tape design

![image](https://user-images.githubusercontent.com/3020266/109389834-ce545d00-78d3-11eb-8c84-dea627cbc534.png)

**Comment by adamjarling** [comment]
@CourtneyMcClellan I'm working on figuring out this issue, and how to pin the tape overly images so they zoom in/out.   Does something like this look on track?

![image](https://user-images.githubusercontent.com/3020266/109502839-210e5000-7a5f-11eb-9038-8edf3470030a.png)

**Comment by adamjarling** [comment]
Note this is without a tint effect, just the tape images.   But thinking about the tint effect, and then the overall UX, I'm wondering how this displays?   

- Is the overlay graphics/effect present at all times?
- Can it be shown/hidden via user control?

**Comment by CourtneyMcClellan** [comment]
Hi Adam,

Yes, this is close to what I am thinking. I think the overlay is in use at
all times (the intention here is to suggest to viewers that they are not
altering the item itself).

I will work to update that image right now.

Thanks,
Courtney

**Comment by CourtneyMcClellan** [comment]
![Curator Annotation JPEG](https://user-images.githubusercontent.com/77364108/109522203-07c7cc80-7a7c-11eb-9685-db3db67ce0c0.jpg)
![My Annotation with overlay JPEG](https://user-images.githubusercontent.com/77364108/109522214-0a2a2680-7a7c-11eb-9207-a9c312a86607.jpg)

**Comment by adamjarling** [comment]
Here's a first pass at applying this to the updated smaller viewport window.  If someone has a better tape image or suggestions, feel free to pass my way.

![image](https://user-images.githubusercontent.com/3020266/115325744-cb4a5000-a151-11eb-8635-7ca3726d2cba.png)

**Comment by adamjarling** [comment]
Comments from @CourtneyMcClellan 

> Added notes: no tape in corners, this design work to remind visitors they are not writing on original item is provided in many other ways.

Ok, I'll pull this feature back and close the issue.
