### ISSUE TITLE
About Page- gallery for viewing LOC Annotation examples

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#21]
On the About Page, Jaime and I have discussed having a gallery of items from the collection that include annotations. Sorry for the confusing, this comment has been edited a couple of time. We landed on a gallery like the one below, so as not to confuse it with the thumbnails which can be annotated.

![image](https://user-images.githubusercontent.com/3020266/104817547-8546be80-57e7-11eb-8fe9-624b8616cd5b.png)

Let me know if there are additional questions. If you want me to create a separate issue for this, I am happy to do so.

**Comment by adamjarling** [comment]
@CourtneyMcClellan Can you try and re-attach the screen shot?   What I usually do in Github, is just copy an image (right-click some image on your computer, and select "Copy").  Then in the text edit part of these Github issues, you can paste the image in, and it usually uploads ok.

**Comment by CourtneyMcClellan** [comment]
[About Page Thumbnail.pdf](https://github.com/adamjarling/loc-speculative-annotations/files/5824702/About.Page.Thumbnail.pdf)


Ok, let me know if this doesn't work.

**Comment by adamjarling** [comment]
@CourtneyMcClellan Yea, for a PDF file this works just fine.  Thanks.

**Comment by adamjarling** [comment]
![image](https://user-images.githubusercontent.com/3020266/104817547-8546be80-57e7-11eb-8fe9-624b8616cd5b.png)

**Comment by jaimemears** [comment]
https://github.com/adamjarling/loc-speculative-annotations/issues/21

**Comment by jaimemears** [comment]
closing - not mvp and entering final sprint.
