### ISSUE TITLE
Pull in new stamp graphics

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#23]
### Description
@CourtneyMcClellan has supplied some new Stamp artwork.  We should incorporate this into the app.

![image](https://user-images.githubusercontent.com/3020266/107584737-a0c49f80-6bc2-11eb-90c1-2aff9565ab0e.png)

### Done looks like 
- [ ] Stamps live in the new Options panel
- [ ] User can filter stamps based on text input
- [ ] Add button moves stamp to page

**Comment by adamjarling** [comment]
@CourtneyMcClellan I'm able to pull in the new stamps ok.  The easiest scenario would be if all the stamps are SVG files, as you've sent over, instead of using other image file types, at least for the Stamp feature.  So basically whatever you sent over works.

One thought, maybe these should be transparent SVG files?

![image](https://user-images.githubusercontent.com/3020266/104847392-555df080-58a5-11eb-8285-354ec639f773.png)

**Comment by CourtneyMcClellan** [comment]
Try these for the transparent SVG file:

 https://drive.google.com/file/d/1IlAGUVLg5s-z8j4z6VT3ekPFQZdBQ2OZ/view?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan Confirmed this way of saving the SVG is transparent on the canvas:

![image](https://user-images.githubusercontent.com/3020266/105802194-48559700-5f60-11eb-9ac0-754279623271.png)

**Comment by adamjarling** [comment]
**_Update February 2, 2021_**

New stamp graphics have been added for all colors.  This is not a feature to be tested during User Testing round 1 though, so pushing back priority.

**Comment by adamjarling** [comment]
**_Messages brought over from a Slack conversation..._**

Adam
If I try to open an SVG file in Illustrator, it asks me to manually select the linked file.  I'm kinda out of my element here:)

Courtney McClellan  5:39 PM
SVG files are new to Olivia and myself so we are figuring it out as we go. We will sort it out

Adam J. Arling  5:39 PM
Transparent PNG files would work great too, for web delivery.

Courtney McClellan  5:40 PM
Ok, that may be easier

Adam J. Arling  5:40 PM
With 100+ images (that we'll have to pre-load) I'd recommend the smallest file size you can arrive at for each stamp image.  SVG might...not totally sure, be the most compressed?  It looks like FabricJS understands both.  PNGs seem a little more straightforward, but apparently I figured out a way to make FabricJS understand SVG images as well when you sent me the sample:).

Courtney McClellan  5:43 PM
Ok, if PNG files are better, we may switch to that. I am going to reach out to Olivia and take a look too

Adam J. Arling  5:45 PM
And for prepping the files, in terms of a naming convention, it'd be awesome and save me a bunch of time if you could use the color in the filename.  For example: `green-star.png` or `pastelBlue-question-mark.png` etc.

Courtney McClellan  5:46 PM
Ok, we can definitely do that! Any notes you have like that bring them on! I am happy to notate in any way that helps

Adam J. Arling  5:47 PM
The current colors which I'm basing off of Jess's pen weight graphics are:

- green
- pastelBlue
- pastelGreen
- pastelPurple
- pink
- teal
- yellow

@CourtneyMcClellan

**Comment by adamjarling** [comment]
Maybe a fill PNG image file with a color solution here?   https://stackoverflow.com/questions/44859026/how-to-select-a-color-fill-it-into-the-selected-image-that-is-uploaded-in-the-c

http://fabricjs.com/image-filters

**Comment by adamjarling** [comment]
@CourtneyMcClellan So it looks like I am able to update the color of a PNG stamp file through FabricJS.  Can you just have Olivia create one color versions of each shape, when you arrive at the final shapes?   I'd make the PNG image files either black or white.

**Comment by CourtneyMcClellan** [comment]
Great! Ok, will do.

**Comment by adamjarling** [comment]
So, turns out SVG files are way easier to handle with the dynamic color switching, in both the Options toolbar, and when adding the Stamp file to the Fabric canvas.  I was able to convert a few of the black PNG files to SVGs in Illustrator, and here's a start on the work:

![image](https://user-images.githubusercontent.com/3020266/108521175-139fdb80-7291-11eb-8cfc-f3e952009376.png)

Note for some reason the Speech Bubble stamp is not respecting the selected color... I'll figure out why over the weekend, and continue building out the rest of the stamps.

**Comment by adamjarling** [comment]
Now updated with all stamps and worked out the bugs.  Closing.
