### ISSUE TITLE
Handle annotating multiple, independent works

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#24]
### Description
Thus far, the prototypes have been working on a single source image.  Now's a good time to shift and start thinking about how a user will select a different work, and add unique annotations.

### Done looks like
- [x] A user can select between works, and the new work appears as the current source image.
- [x] Each work is uniquely identified in the URL somehow (for sharing and saving)
- [x] Create a mapping object (maybe IIIF manifest) to document all available works to the application.  This will also drive the UI for "select a new work" component.
- [x] "Save canvas" saves user annotations specific to a work
- [x] "Share" uses a URL which uniquely identifies a LOC source image on which to re-create user annotations

**Comment by adamjarling** [comment]
Before moving forward on the "Save" part, I should verify that we want annotations to be tied directly to a specific LOC image.  Or... should annotations exist independently from LOC images, and be able to be applied to any and all LOC images?

**Comment by CourtneyMcClellan** [comment]
Hi Adam-- yes, each annotation drawing should be specific to the item. Therefore, if a new item is selected the canvas should start of clean. Subsequently, the previous canvas would have needed to be saved, or it will be lost.

**Comment by adamjarling** [comment]
This is now working where a user annotation is synced to a work.

I do have a quick question on the My Annotations list, @jessvu.  The annotation title is able to be edited and saved in-line.  Do we still want the "Edit" link on the right?  I assume this is supposed to edit the title?  

![image](https://user-images.githubusercontent.com/3020266/106550192-45b2ee80-64d8-11eb-88de-ae496d3890df.png)

**Comment by CourtneyMcClellan** [comment]
Hi Adam,

To confirm I am understanding the question: Are we considering if someone
can reopen and continue to work on a saved annotation?

Thanks!
Courtney

**Comment by adamjarling** [comment]
Hey @CourtneyMcClellan So the way I'm understanding the UX document (which very well could be incorrect:), is in the annotations list, clicking on the "arrow" will switch immediately to the saved annotation and work.

Clicking the trash can button will delete the record of the annotation saved in the user's browser, but won't immediately change anything on the screen.

I assumed "Edit" would be editing just the saved annotation's title?   But now that I'm looking at it, maybe "Edit" means to actually switch and go to the the saved annotation itself?   And maybe the "arrow" means to share?   

Guess I need some clarification.

Additionally, I'm not sure we'll be able to offer a preview of the saved annotation (the tomato colored placeholder box), if we're not saving any data (images) to a server.   We'll need to think through this.

**Comment by CourtneyMcClellan** [comment]
Ok, yeah I am not sure I understand either. So let's ask Jess for
clarification. Also, I will have some time to spend taking a look today.

Jes, do we still need the Edit button, if so, what should we expect it does?

**Comment by jessvu** [comment]
I was imagining that the 'Edit' button would be linked text and allow the user to edit the saved annotation itself, and yes, the arrow would mean to share. If we can't have a thumbnail image, then a title might be enough. Since there was confusion about what 'edit' means I will think through solutions to make that more clear.
