### ISSUE TITLE
UX Feedback

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#25]
Here is a working slide deck for UX feedback as the application evolves. It includes UX recommendations as well as visual examples that are all open for discussion. Let me know if you have any questions!

https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gb70299d777_0_53

**Comment by adamjarling** [comment]
Here are some initial screen shots from the new wireframe layout:

![image](https://user-images.githubusercontent.com/3020266/105604815-a06f7c00-5d5b-11eb-8b4f-26350542fed0.png)

![image](https://user-images.githubusercontent.com/3020266/105602950-1cb58f80-5d5b-11eb-9d94-ec44de36c333.png)

![image](https://user-images.githubusercontent.com/3020266/105602472-fbed3a00-5d5a-11eb-9f24-9f49db9918f4.png)
