### ISSUE TITLE
Text tool UX cleanup

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#28]
Experiment with either adding text directly to the canvas via click (which I ran into issues with before), or drag and drop sample text onto the Fabric canvas.  In both cases, we'll need an edit toolbar to appear allowing user to customize:

- font size
- background color
- font face
- more?

![image](https://user-images.githubusercontent.com/3020266/105607793-91da9200-5d66-11eb-81ed-f668ff79f74d.png)

### Done looks like
![image](https://user-images.githubusercontent.com/3020266/105784762-0a944680-5f3f-11eb-8c8f-084601d64845.png)

![image](https://user-images.githubusercontent.com/3020266/105785364-52679d80-5f40-11eb-8b7c-6c661fc73045.png)

![image](https://user-images.githubusercontent.com/3020266/105785486-a2466480-5f40-11eb-80fa-91f05f2a28da.png)

- [ ] User should be able to see a preview of what their text will look like by typing in the text box. 
- [ ] The text style will automatically apply and update live. 
- [ ] User could then select desired text style click anywhere on the canvas to place their text and begin typing.
- [ ] The toolbar on the left (screen shot below) is the main toolbar, and the adjustment toolbar that appears when clicking on the elements on the canvas is dynamic and catered to the type of element the user selects such as a shape or a text

**Comment by adamjarling** [comment]
@jessvu If I run with the first solution of allowing a user to point and drop text, what's the best way to show their edit options?  

![image](https://user-images.githubusercontent.com/3020266/105608578-5b524680-5d69-11eb-9dbb-59490603eb99.png)

Here's a first attempt at using the same dynamic options bar as in Draw.

![image](https://user-images.githubusercontent.com/3020266/105614884-f52de980-5d91-11eb-9f97-8a61e95438d5.png)

**Comment by adamjarling** [comment]
@jessvu Do we want the 'Add' button in the Font Preview panel above?

**Comment by jessvu** [comment]
@adamjarling  I don't think we would need the 'add' button if the user is selecting the font they want and then clicking on the canvas to place the text where they desire

**Comment by jessvu** [comment]
![image](https://user-images.githubusercontent.com/32075716/105937195-0c373a80-6023-11eb-918a-2a77cdfc5c64.png)

**Comment by jessvu** [comment]
![image](https://user-images.githubusercontent.com/32075716/105937219-19542980-6023-11eb-827e-6728700f236a.png)

**Comment by adamjarling** [comment]
Closing this issue, to capture the intended scope of the feature during prototype phase.  There's a new issue for refining the Type tool for User Testing round 1.
