### ISSUE TITLE
Shape Tool Mockup

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#29]
![image](https://user-images.githubusercontent.com/32075716/105937288-3f79c980-6023-11eb-90e8-25bd15fe5486.png)

**Comment by adamjarling** [comment]
@jessvu @CourtneyMcClellan FYI, Fabric supports the following shapes:

fabric.Circle
fabric.Ellipse
fabric.Line
fabric.Polygon
fabric.Polyline
fabric.Rect
fabric.Triangle

http://fabricjs.com/fabric-intro-part-1#objects

Initially, this is what we'll have to work with if that's ok?   At least for user testing.

**Comment by adamjarling** [comment]
Same icon issue as before, if suitable icons are not available through https://react-icons.github.io/react-icons/search, then we might need to create some custom icons like Jessica provided earlier this week (which I still need to plug in and make sure they work:)

**Comment by CourtneyMcClellan** [comment]
This works for me, thanks Adam!

**Comment by adamjarling** [comment]
@CourtneyMcClellan Here's what the initial icons look like from the React Icons package.  I'll push up this UI, but it's not wired up yet.

![image](https://user-images.githubusercontent.com/3020266/106151517-0b48fa80-6142-11eb-85cc-d3cae107323c.png)

**Comment by adamjarling** [comment]
This is now add all the shapes to the screen, relatively bug free.
