### ISSUE TITLE
Prototype - Drawing

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#3]
## Description
Draw on the image - palette of 4 or 5 colors based on SA palette- kinds of lines include a marker, a crayon, a pencil.

### Example
Canvas Chrome App

![image](https://user-images.githubusercontent.com/3020266/103356483-99b05a80-4a76-11eb-968f-8e365aeb8b49.png)

### Reference link
(Beginning at 3:35) https://www.youtube.com/watch?v=kPQahvtv6Kw

**Comment by jaimemears** [comment]
After I select my color and thickness, I want to start drawing immediately. Difficult to remember to select “start drawing” before I begin.

**Comment by jaimemears** [comment]
When I draw on my iPad, I accidentally set off the rotation and size affordances on existing drawings, especially when I want to layer color. These make sense for stamps, but I wonder if we need them at all for drawing?

**Comment by jaimemears** [comment]
Can the ux design of this mimic the stamp tool and others? ie - when you select the paintbruch a side panel pops out with the colors and thickness options? Get rid of the "settings" step in the ux flow.

**Comment by adamjarling** [comment]
@jaimemears Gotcha.  I'll try to incorporate all the feedback above and see how we can smooth out the UX.

**Comment by adamjarling** [comment]
Closing for the prototype phase.

![image](https://user-images.githubusercontent.com/3020266/106362087-94993200-62e6-11eb-9ca0-e0c53e0bccaf.png)
