### ISSUE TITLE
Update saving and displaying a user's annotations based on UX Feedback

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#31]
Based on UX feedback, update how saving and selecting saved annotations are being handled.

‘Annotate’ is a drop-down menu that holds the option to create a new annotation and view saved annotations. If a user does not have any saved annotations a modal will still appear and show an empty state.

![image](https://user-images.githubusercontent.com/3020266/106362180-08d3d580-62e7-11eb-8bbf-53025fa503ed.png)

![image](https://user-images.githubusercontent.com/3020266/106362391-30776d80-62e8-11eb-87ce-198fd1977e34.png)

**Comment by adamjarling** [comment]
Based on a recent conversation with @jessvu about what "Save" really means, we may need to re-think this feature.

**Comment by jaimemears** [comment]
@adamjarling are you clear here on what’s needed for Save or do I need to assign to Jessica for comment?

**Comment by adamjarling** [comment]
@jaimemears @jessvu This modal is just placeholder UI and needs clarification or a decision on whether we're moving forward with it.  I'm not sure we ever revisited how we're approaching "Saving" (local annotations to a Work) vs. "Downloading" an image file.   

If we're going to keep the Save functionality, I'll need to block a decent amount of time to make sure it's tightened up.

**Comment by jaimemears** [comment]
When you say "saving" local annotations to a work do you mean saving the annotations within the application environment, like we tried to do with the persistent link?

**Comment by adamjarling** [comment]
Yea, "Saving" (in my mind, but open to alternate terminology), is saving the current Fabric JS JSON object (containing user annotations), to the user's browser's `localStorage`.  This data only saves in a specific browser, will not work in "private" browser mode, and will be lost if the user clears their browser application data cache.

Saving "saves" annotations to a specific work.  So a user could potentially save different annotations for different works.  The functionality which warns a user when switching would need to still be built in, if we're going to move forward and use this feature.

**Comment by jaimemears** [comment]
I understand. And being able to pass or share the Fabric JS JSON object is impossible even if we get the save functionality to work in this way correct? Because its in local storage, and we'd need a server or something to share?

**Comment by adamjarling** [comment]
@jaimemears Sharing a current user annotation currently does work and is functional, it just creates a share URL which is humongous due to the size of the FabricJS JSON object (which is compressed as much as possible).   

This process could probably be streamlined to provide better UX, by building a simple back-end service.

**Comment by jaimemears** [comment]
oh i thought after 4 or 5 annotations the url no longer would render in a browser because it was so long?

**Comment by adamjarling** [comment]
This is a possibility, but I never really thoroughly tested it's limits.  After one annotation object (ie. a Circle or Stamp), it's pretty long so yea more complex ones just make the compressed url longer.  I can test this though and see where or if it maxes out?   If, we think we might want to keep this functionality as-is?

**Comment by CourtneyMcClellan** [comment]
Seems removing the share functionality, can we close this?

**Comment by adamjarling** [comment]
@CourtneyMcClellan Yes, we can close the issue

**Comment by adamjarling** [comment]
Note this functionality (the UI components) will be left in place and documented for possible future integrations.

**Comment by CourtneyMcClellan** [comment]
Can we close this?

**Comment by adamjarling** [comment]
@CourtneyMcClellan, @jaimemears was asking about this and we had a Slack conversation about the functionality of "saving" previous revisions.  Sounds like she was leaning towards not including that functionality in this release, and if you two want to confirm that decision, then yes we can close this issue I'd say.

**Comment by CourtneyMcClellan** [comment]
Ok, I think Jaime has an additional question. I will let her pose it before
we decide about closing.

**Comment by jaimemears** [comment]
@adamjarling has estimated 4-8 hours of work for this issue to be implemented. Assigning to @CourtneyMcClellan . This is a tough call!

**Comment by adamjarling** [comment]
Pushing up round one of what this would look like.  Note it still may be a bit buggy, but hopefully this gives the general idea and how it'd act more or less?

**Comment by CourtneyMcClellan** [comment]
This seems great and is working well for me!

**Comment by jaimemears** [comment]
closing this, courtney is satisfied with the save functionality
