### ISSUE TITLE
Type Tool Feedback

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#34]
![image](https://user-images.githubusercontent.com/32075716/106690394-ba9d2b80-659f-11eb-8164-96d21b67a92d.png)

https://docs.google.com/presentation/d/1GPby059FlA5RSSo-xBiE1HTkOOstBC17VkPuwfrTWzA/edit#slide=id.gb5e38bc965_0_16

**Comment by adamjarling** [comment]
Possible solution:  https://stackoverflow.com/questions/30632816/how-to-activate-the-cursor-for-a-fabric-js-itext

**Comment by adamjarling** [comment]
Just pushed up some changes to the Type Text tool.
- User can now just click anywhere on the canvas and start typing
- When clicking off an active typing object, it resets itself.  Previously it jumped straight into a new type action.
- Added in mouse cursor support based on whether user is actively typing, and when not actively typing.

![image](https://user-images.githubusercontent.com/3020266/107161528-d79c7a80-6962-11eb-8a82-bfa8f39a1fcb.png)

**Comment by jessvu** [comment]
**Feedback for Text Tool Update**

<img width="1679" alt="Screen Shot 2021-02-07 at 8 52 06 PM" src="https://user-images.githubusercontent.com/32075716/107167265-7090bd00-6986-11eb-9cbe-d33889ad2c23.png">

<https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gbc2a418f24_0_0>

<img width="1679" alt="Screen Shot 2021-02-07 at 8 52 14 PM" src="https://user-images.githubusercontent.com/32075716/107167423-da10cb80-6986-11eb-9e47-838852a36c2f.png">

<https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gbc2a418f24_1_7>

**Comment by adamjarling** [comment]
@jessvu  Something like this?

![image](https://user-images.githubusercontent.com/3020266/107302232-ac895800-6a42-11eb-8fa2-63d31f8227e3.png)

![image](https://user-images.githubusercontent.com/3020266/107302283-c165eb80-6a42-11eb-96ff-bc9d14f84d8b.png)

**Comment by jessvu** [comment]
@adamjarling yes, exactly!

**Comment by adamjarling** [comment]
@jessvu This should be in place where the text cursor is the currently selected global color.  Fabric gives it this fade in / fade out, like its breathing type effect which not sure I can control.  I just checked in Chrome/Brave/Safari.   If you're not seeing it, can you let met know which browser?  And are you on Mac or PC?  I'll pop this open in Browserstack and run it through all options if we can't track it down.

![image](https://user-images.githubusercontent.com/3020266/107303087-063e5200-6a44-11eb-88ba-104fcdb673c2.png)

**Comment by adamjarling** [comment]
I can also control the background color (including opacity) and edit box border color.  Currently I have the background "white" with a `0.5` opacity value.

**Comment by jessvu** [comment]
@adamjarling this is what I'm seeing. When I select the type tool, I'm seeing a crosshair cursor instead of a text cursor. The crosshair cursor gives the impression that a text box could be drawn while a text cursor indicates that I may begin typing immediately. However, this isn't a huge usability concern of mine at this point. I think users should be able to figure out how to use the text tool with little to no problems. As for the color, I think for now your settings are fine. 

https://user-images.githubusercontent.com/32075716/107303732-9f259b00-6a4d-11eb-93fb-74a28c7ecc59.mov

**Comment by adamjarling** [comment]
Yea, I have the crosshair issue fixed.  I'll push up the fixes now...

**Comment by adamjarling** [comment]
FYI, for browser supported cursors, here's a list.  I'll look into how to get a paintbrush as an icon through FabricJS too.

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#values
