### ISSUE TITLE
Color Picker + Shape Tool Feedback

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#35]
![image](https://user-images.githubusercontent.com/32075716/106690443-d0aaec00-659f-11eb-9462-7fcf247e5873.png)

https://docs.google.com/presentation/d/1GPby059FlA5RSSo-xBiE1HTkOOstBC17VkPuwfrTWzA/edit#slide=id.gb5e38bc965_0_23

**Comment by jessvu** [comment]
**Feedback for Shape Tool**
<img width="1679" alt="Screen Shot 2021-02-07 at 8 52 20 PM" src="https://user-images.githubusercontent.com/32075716/107167539-1ba17680-6987-11eb-8c31-fdd49c171ce4.png">

<https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gbc2a418f24_0_11>

**Comment by adamjarling** [comment]
I'll start digging into the possibilities with this tomorrow.

**Comment by adamjarling** [comment]
Some possible solution routes:  
- https://codingsans.com/blog/fabricjs-tutorial
- http://jsfiddle.net/a7mad24/aPLq5/

**Comment by adamjarling** [comment]
Created a new issue to address the dragging and sizing of a new Shape:  https://github.com/adamjarling/loc-speculative-annotations/issues/39. 

Closing this issue.
