### ISSUE TITLE
Add Manuscript items 

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#36]
Could we add these two items so they are available for user testing tasks? I have provided the urls below and jpg versions.

Item 1:
https://www.loc.gov/resource/magbell.25300102/?sp=33

![service-mss-magbell-253-25300102-0033](https://user-images.githubusercontent.com/22895272/106800602-aa805d00-662e-11eb-8b2e-237ad6292fc0.jpg)

Item 2:
https://www.loc.gov/resource/mss18630.03706/?sp=13&r=0.375,0.426,0.944,0.375,0

![iiif-service_mss_mss18630_037_06_013-full-pct_50-0-default](https://user-images.githubusercontent.com/22895272/106800568-9d636e00-662e-11eb-8ccb-ecf7820eb291.jpg)

**Comment by adamjarling** [comment]
@jaimemears I have the images added to the app now.

![image](https://user-images.githubusercontent.com/3020266/106899543-1a3c2980-66bb-11eb-86f0-a757f41549a8.png)

For the Walt Whitman image, I was able to dig in and find the IIIF image service file (https://tile.loc.gov/image-services/iiif/service:mss:mss18630:037:06:013/info.json), which let's us grab the image hosted in a IIIF server.   However I couldn't locate the same `info.json` file for the Bell image.  I just pulled a source .jpg from the link.  Maybe this is ok?

**Comment by adamjarling** [comment]
@jaimemears If you want to review the local metadata I'm tracking for the LOC works in the app for accuracy, here's a link:   https://github.com/adamjarling/loc-speculative-annotations/blob/main/src/services/loc-images.js

Let me know any adjustments?

**Comment by jaimemears** [comment]
I just popped the question about whether the Bell drawing is also available on our IIIF server. Stay tuned. Local hosting is just fine for user testing and probably will need to happen for some even in production if they are not availabl in IIIF.

**Comment by jaimemears** [comment]
ok here's what i got - "this iiif image API url works: https://tile.loc.gov/image-services/iiif/service:mss:magbell:253:25300102:0033/full/full/0/default.jpg - however, since there are not jpeg2000s for these images, we don't publish the iiif url due to the performance implications of deriving from non-jp2 sources. @thatcher is really the expert and may have thoughts on this."

**Comment by adamjarling** [comment]
Pulled in the new IIIF service image URL above. Closing this issue as both items are now included in the app.
