### ISSUE TITLE
Apply style guide base styles and fonts

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#37]
Given this latest document, apply some of the style guide colors/fonts where applicable.

[style-guide-usage.pdf](https://github.com/adamjarling/loc-speculative-annotations/files/5935803/style-guide-usage.pdf)

![image](https://user-images.githubusercontent.com/3020266/107099583-ac395480-67d7-11eb-92ea-53caec7ad852.png)

![image](https://user-images.githubusercontent.com/3020266/107099608-bbb89d80-67d7-11eb-9ad0-ce3dfce63b15.png)

![image](https://user-images.githubusercontent.com/3020266/107099628-cc691380-67d7-11eb-91b3-0bc1bbda8dc0.png)

**Comment by adamjarling** [comment]
@CourtneyMcClellan Is the font "ocr a std" to be used everywhere?   Looks like the sample navigation font is different.  Can you clarify usage, and if there is a secondary font for nav or anything else, what the font family is?

**Comment by CourtneyMcClellan** [comment]
Hi Adam,

OCR a Std is to be used for headers, or any major label, for example Teach,
Annotate, About should be in that font. It is the font in the logo.
It is a good question about the font for body text, for example in the
About and Teach text below the header. Let me think on that and get back to
you.

Let me know if I have not answered your question!

Cheers,
Courtney

**Comment by CourtneyMcClellan** [comment]
Let's go with Open Sans for the body text, which is also on that design
sheet for the tool font section.
