### ISSUE TITLE
Drag and size new Shape object

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#39]
**Feedback for Shape Tool**
<img width="1679" alt="Screen Shot 2021-02-07 at 8 52 20 PM" src="https://user-images.githubusercontent.com/32075716/107167539-1ba17680-6987-11eb-8c31-fdd49c171ce4.png">

<https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gbc2a418f24_0_11>

**Comment by adamjarling** [comment]
Some possible solution routes:  
- https://codingsans.com/blog/fabricjs-tutorial
- http://jsfiddle.net/a7mad24/aPLq5/
- https://codepen.io/subhasishwebdev/pen/jyOeya

**Comment by jessvu** [comment]
Not necessary for user testing, but when you are able to get to it– when a user selects the shape tool, could you change the cursor to be a crosshair cursor to indicate that the shape can be dragged out?

**Comment by adamjarling** [comment]
Crosshair updated per comments above, and fixed Arrow deletion problem.   

Making the Star shape not a priority, per @CourtneyMcClellan 's suggestion.  Closing this issue for now and can refine with new issues.
