### ISSUE TITLE
Prototype - type text on image

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#4]
## Description
A way to type anywhere on the image - a selection of several types of fonts

### Resources
- http://fabricjs.com/loadfonts

**Comment by jaimemears** [comment]
Possible to have a transparent background option?

**Comment by adamjarling** [comment]
@jaimemears Yes, I'll make the switch and include in the next update.

**Comment by jaimemears** [comment]
I gotta say I'm loving the "qui et optio" example font in this. I'm wondering if its possible to toggle between transparent background and white for the text boxes? I could see how both would be useful, given different types of images and how busy they are.

**Comment by jaimemears** [comment]
The sizing fitted to a single word so that they appear in a stack makes it hard to read. Ideally the sizing would match the width of the box you write text in - about 5-7 words across?

**Comment by adamjarling** [comment]
This is pretty decent for the Prototype phase.

![image](https://user-images.githubusercontent.com/3020266/106362018-218fbb80-62e6-11eb-8968-d943d1f9c4bf.png)
