### ISSUE TITLE
Overlay Views

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#40]
@adamjarling If you are able to make this update quickly, could you add the 'Change Display' label and icon before the display options and make the default set to view 'Your Annotations'? However, since this feature isn't functional yet, could you disable the whole component so that the user doesn't try to check and uncheck anything?

If this isn't a quick change/you would rather spend your time focusing on other features, could you hide the component all together? Thanks Adam!

![image](https://user-images.githubusercontent.com/32075716/107717665-31be7800-6ca2-11eb-8375-634d31789abc.png)

**Comment by adamjarling** [comment]
@jessvu Here's how this looks...  The checkboxes are set to be disabled, and if you hover over each you'll see the standard accessibility disabled overlay, however you can still check / uncheck each control.    If you'd rather this whole section is hidden, let me know and I'll hide it.

![image](https://user-images.githubusercontent.com/3020266/107773302-1172d580-6d03-11eb-929f-7173920f74fe.png)

**Comment by adamjarling** [comment]
Closing for now as the feature is active.
