### ISSUE TITLE
Curator Annotation

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#41]
When this is toggled to within an item, a jpg file of the item with curator annotations is displayed. Tool functionality is available to add additional annotations to the image, same as “My Annotation” mode. Overlay design must visually signal that this is the “curator” view.

**Comment by jaimemears** [comment]
@CourtneyMcClellan could you or your design contractor provide an example of what you’d like the curator view to look like ideally? I’m imagining its the exact same as the “my annotation” view but with a color change or something to signify that its different from “my annotation”.

**Comment by adamjarling** [comment]
Just to make sure I'm understanding this correctly, here's how I'm interpreting:

- When curator annotation is toggled, then the current source image is _replaced_ with a new, flat JPG image which contains all the curator's annotations.  
- Curator annotation is _not_ a Fabric JS overlay object (similar to how we were "saving" a user canvas before).
- We'll use FabricJS to create some type of image filter, or add a new Fabric image object to the Fabric canvas, which indicates it's a curator annotation canvas.
- User will be able to use all current tools to annotate the new source image.

If I'm missing anything above, let me know?

**Comment by jaimemears** [comment]
Yes, that’s right!

Sent from my iPad

On Feb 17, 2021, at 8:44 AM, Adam J. Arling <notifications@github.com> wrote:

﻿

Just to make sure I'm understanding this correctly, here's how I'm interpreting:

  *   When curator annotation is toggled, then the current source image is replaced with a new, flat JPG image which contains all the curator's annotations.
  *   Curator annotation is not a Fabric JS overlay object (similar to how we were "saving" a user canvas before).
  *   We'll use FabricJS to create some type of image filter, or add a new Fabric image object to the Fabric canvas, which indicates it's a curator annotation canvas.
  *   User will be able to use all current tools to annotate the new source image.

If I'm missing anything above, let me know?

**Comment by adamjarling** [comment]
@jaimemears For this feature, we have one of two options to display the Curator Annotation image.  

- It's either hosted somewhere at LOC and you give the app the URL, or 
- We use local versions of the images

Think you could get local derivative versions of the JPGs for the 4 images we're currently using?   We can always add the annotations later, but it will help me get the sizing right swapping images.

**Comment by adamjarling** [comment]
@jaimemears Actually I was able to pull local images from where they're currently hosted.  I can use these for testing, and see if the sizing matches up.   No rush on getting source images, but something to think about... preparing somewhat realistic versions of the Curator Annotation images, just so we're prepared and no surprises on implementing them.

**Comment by adamjarling** [comment]
UX Recommendations for how to handle My Annotations / Curator Annotations:

![UX Review of Features](https://user-images.githubusercontent.com/3020266/109301098-0a68be80-77fd-11eb-8aa6-ad0dcc4fe00c.jpg)

![UX Review of Features (1)](https://user-images.githubusercontent.com/3020266/109301074-0177ed00-77fd-11eb-8869-6035a183e720.jpg)

![UX Review of Features (2)](https://user-images.githubusercontent.com/3020266/109301057-fae97580-77fc-11eb-9a04-19af09c09326.jpg)

![UX Review of Features (3)](https://user-images.githubusercontent.com/3020266/109301032-f0c77700-77fc-11eb-8787-78d7b31832ea.jpg)

**Comment by adamjarling** [comment]
Pushing up changes now which reflect the UX suggestions:

![image](https://user-images.githubusercontent.com/3020266/109309747-4efa5700-7809-11eb-940c-42dc68a15da1.png)

![image](https://user-images.githubusercontent.com/3020266/109309806-5de10980-7809-11eb-9fa5-eb9976de80a9.png)

**Comment by adamjarling** [comment]
There are some sample "Curator Annotation" images I created in here fyi (The LOC watermark across the images).

**Comment by jaimemears** [comment]
Im so excited! I have a user test at 1130 with someone from our office of communications and we can try these out!

**Comment by CourtneyMcClellan** [comment]
Yes, we can work on that.

**Comment by adamjarling** [comment]
Closing as the initial functionality and UX seems to meet the context of this issue. 

### Next Steps:
- Get the real Curator annotated versions of the source images.
- Or (if the Curators wanted to make their annotations with SA's tools), we could also capture the Fabric JS object, copy and paste the file, send to me and I can use that to do a "read-only" overlay perhaps?   We'll have to see how this goes...

**Comment by CourtneyMcClellan** [comment]
Ok, sounds good. Ideally, the curators would use SA to annotate the image.
This will take some institutional as well as technical finagling. Jaime and
I are meeting tomorrow, we will discuss and share thoughts.

Thanks!

**Comment by adamjarling** [comment]
Ah, ok.  Well if that's the case, and Curators will want to add any annotations outside of the borders of the source image, then it's going to be easiest to go route 2 from above options.   They could probably use the existing "Share" feature, copy and paste that and somehow pass my way to plug into the app as a Saved Annotation.  

I'll need to play with this and make sure I can make the curator's annotations read-only...so will re-open this issue and work on that this week.

**Comment by adamjarling** [comment]
Curator Annotations are now stored as Fabric JS objects, instead of creating parallel "curator" .jpg files for each source image.

The Curator Annotations are also referenced in each Work's IIIF Manifest.  It's just test annotations in there now, but the app will know whether Curator Annotations exists or not and update the UI accordingly.  

The general structure of how this works in the IIIF manifests goes something like:

- `public/iiif/speculative-annotations-manifest.json` is the parent file for all IIIF manifest data and stored as a type `Collection`.
- Each LOC work is represented by it's own IIIF manifest of type `Manifest` under the `Collection`
- A LOC work may have an `annotations` property, which will list annotations in accordance with the IIIF 3.0 spec.
- For now, the Curator Annotation objects are stored under a relative path.  For example the Zora Neil Hurston LOC work, that path is `iiif/zora-neil-hurston/annotation/curator001/info.json`

For more info, reference the directory structure in the app under the `public/iiif` directory to see how things are laid out.  @jaimemears and myself have a meeting scheduled to walk through this as well.
