### ISSUE TITLE
Stamps Display

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#42]
Hi Adam, I noticed that when I open the Stamps tool panel it opens up underneath the tools at the bottom of the app. In the screenshot that you took it doesn't seem to be an issue so this could be a Mac thing. For desktop, would it be possible to display it so that the user is shown 20 stamps at a time (2 columns of 10) and allow users to scroll through the stamps? The display may need to change to fit mobile screens, but we can decide that at another time.
![image](https://user-images.githubusercontent.com/32075716/108640387-4ef40300-7467-11eb-89b5-35f8dc7e859b.png)

**Comment by jessvu** [comment]
And this is not urgent for user testing (also apologies if I'm starting to sound repetitive as you might already be working on this functionality) but if possible could we allow users to be able to drag and drop stamps onto the canvas? I think that would make for a more intuitive experience.

**Comment by jessvu** [comment]
@adamjarling here are my UX recommendations for the Stamps tool
![image](https://user-images.githubusercontent.com/32075716/109569340-4aa69600-7ab6-11eb-99cd-08f9b5de7a01.png)

**Comment by adamjarling** [comment]
For the drag and drop functionality?  https://codepen.io/Prebyter/pen/ggVxWo

**Comment by jessvu** [comment]
@adamjarling yes, I think that functionality works well! Could you also make the anchor points for dragging/adjusting the size of the elements more prominent? A high-contrast blue outline with white fill on the anchor points seems to be common in similar tools: 
<img width="276" alt="Screen Shot 2021-03-02 at 7 39 41 AM" src="https://user-images.githubusercontent.com/32075716/109650132-d0fcbf80-7b2a-11eb-9276-f4fd186a134e.png">
<img width="395" alt="Screen Shot 2021-03-02 at 7 38 47 AM" src="https://user-images.githubusercontent.com/32075716/109650133-d1955600-7b2a-11eb-8c04-7aa213fa9e98.png">

**Comment by adamjarling** [comment]
@jessvu Working on this all morning and I have the drag and drop functionality working, however it's not precisely dropping at the point on the canvas quite yet.  Need to possibly re-size the SVG images so they're all consistent height, or figure out some offset math for getting it to look right responsively.  This might take me a little time fyi to figure out.

**Comment by adamjarling** [comment]
@jessvu @CourtneyMcClellan To get the filter stamps feature added, we'll need to name each stamp.   Could someone create some stamp names/titles and post in this issue?  I don't really trust myself on the naming:).  The stamps are numbered as seen below... so a perfect format would be:

Stamp1: Speech bubble
Stamp2: Speech bubble
Stamp3: Circle
...etc.

![image](https://user-images.githubusercontent.com/3020266/109973511-1a314880-7cbe-11eb-8895-1033035c2e7e.png)

**Comment by adamjarling** [comment]
Pushing the updates now.... current status is that Drag and dropping onto the Fabric canvas is functional in Desktop, but NOT mobile.  I'll create a new issue for that.

**Comment by CourtneyMcClellan** [comment]
Yes, I will take care of this now.

**Comment by CourtneyMcClellan** [comment]
Stamp1: Speech bubble
Stamp2: Speech bubble
Stamp3: Speech bubble circle
Stamp4: Long speech bubble
Stamp5: Insert
Stamp6: Thought bubble
Stamp7: Ampersand
Stamp8: idea light bulb
Stamp9: Period
Stamp10: Ellipses
Stamp11: comma 
Stamp12: Eye
Stamp13: parenthesis L
Stamp14: parenthesis R
Stamp15: Exclamation point
Stamp16: Hastag
Stamp17: Bracket L
Stamp18: Bracket R
Stamp19: Astrick
Stamp20: Sound

**Comment by adamjarling** [comment]
@CourtneyMcClellan Mind naming these as well?

![image](https://user-images.githubusercontent.com/3020266/109977212-37681600-7cc2-11eb-8c7a-98785780139e.png)

**Comment by CourtneyMcClellan** [comment]
Will do!

**Comment by jaimemears** [comment]
Courtney to add 8 additional stamps. Assigning ticket to Courtney.

**Comment by CourtneyMcClellan** [comment]
Is there anything left to do here? If not, let's close it.

**Comment by adamjarling** [comment]
I think the only thing left is to give me names/titles of the stamps from above, so they can be included in the Stamps search box.

**Comment by CourtneyMcClellan** [comment]
Since we removed the search capability, can we close this issue?

**Comment by adamjarling** [comment]
Yea, closing now.
