### ISSUE TITLE
Convert metadata panel source info file to IIIF 3.0 manifest

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#45]
### Description
With an eye towards possibly saving out annotations, we could store metadata surrounding source images in IIIF 3.0 compliant manifest files.   Then parse this info (via manifesto.js maybe if not too heavy?) for rendering into the application.

**Comment by adamjarling** [comment]
@jaimemears This relates to #51  somewhat... I was just reading through the IIIF meeting notes from Glen, Josh and Meg, and was wondering about a comment you made regarding other Library systems or organizations using this app.  

One way would be to host this app's code on their own website/server of course, and they could feed the application whatever images they wanted.

Another way others could use the app, would be if the SA app was hosted by LOC, and outsiders fed in their own IIIF manifests (through a form input pointing to a IIIF manifest URL, or file upload), which imported a user IIIF manifest which contains references to their IIIF hosted images.  And the application would dynamically update it's source images, instead of hard-coding them like we're doing now.

Just curious on if this is what you may have been thinking?

**Comment by jaimemears** [comment]
For the second example….. when you say LC hosting it, what does that entail? How would we be able to signal that images fed in from other institutions were not our own? Would it exist as a separate dockerized instance on our server space available as a shell for others to use?

Thanks!

**Comment by adamjarling** [comment]
@jaimemears For option 2, nothing that technical.  I was referring to "hosting" as just whatever hosting environment this application lands.  What I was referring to is the act of selecting images being part of the application itself.  A lot of IIIF UI interfaces are designed to be agnostic to source materials, and then you feed generic apps IIIF manifests and they display the content.  

Not suggesting we go this route, but thought one of your comments in the email thread from Josh/Glen/Meg was asking about extending the app's functionality to other institution's materials. 

We can chat more about it if it's still unclear.

**Comment by adamjarling** [comment]
As of this PR (https://github.com/adamjarling/loc-speculative-annotations/commit/8f3da7a210e632c18982bb27f48713ecf57c8552) Work's metadata is now being delivered by IIIF manifests.

Since this is a single page application, we can't really serve the manifests so for now we'll store the IIIF JSON manifests in `/public/iiif` in order to mimic Promise-based retrieval.  

The top-level application IIIF manifest is `public/iiif/speculative-annotations-manifest.json`, which a `type: Collection` manifest storing information about all containing works and the application itself.

In the top-level manifest, the `items` property holds the individual manifests for each Work, which holds all the metadata for each work.

In the `public/iiif/` folder, there are numerous folders which each represent either a local application Work, or a very simple IIIF manifest file which represents the parent LOC collection (or search if a collection is not referenced by @jaimemears ) that contains the Work.

```
/iiif
  /duchess
  /federal-threatre-project
    info.json
  /national-park
  /wpa-posters
    info.json
...
```

**Comment by adamjarling** [comment]
@jaimemears I'm putting this into the "Needs feedback/action" Project column in the Github project, in case you'd like to schedule a bit of time to go over the general structure of how these Manifests are organized, and how we'd go about updating them on either of our ends?

**Comment by jaimemears** [comment]
Sounds great. When do you want to chat about it? Im generally free Monday and Tuesday evenings.

**Comment by adamjarling** [comment]
@jaimemears I could do tonight if you'd like?  I'm free anytime after 6pm.   Zoom or something with screen share will probably be helpful?   If you want me to set something up, lemme know?

**Comment by jaimemears** [comment]
Im free most Tuesdays, except for this one! Next Tues?

**Comment by adamjarling** [comment]
Sure thing, that works.

**Comment by adamjarling** [comment]
From @jaimemears 

https://www.loc.gov/item/mal0063800/manifest.json

_...our developer said that there should be manifests for most thinks if you use that file structure. if you get a 500 or error, lmk and i can slack them to fix the issue._

**Comment by adamjarling** [comment]
### LOC IIIF manifest locations:

**National Park manifest:**
https://www.loc.gov/item/2007676133/manifest.json

**Walt Whitman:**
https://www.loc.gov/item/mss1863001302/manifest.json

**Duchess**
https://www.loc.gov/item/ihas.200218724/manifest.json

**Filmstrip**
https://www.loc.gov/item/2007660344/manifest.json

**Ice cream soda**
https://www.loc.gov/item/2017819414/manifest.json

**Comment by jaimemears** [comment]
Cool so the manifests are there so far! How’s the parsing looking btw 2.0 ->3.0?

**Comment by adamjarling** [comment]
@jaimemears Yes, pulled the LOC manifests into the SA application and am pushing updated code now.   The application now is using a hybrid of LOC hosted manifests for data, and our local 3.0 manifests.

So basically the parent Collection manifest (our own) contains an `items` array of Works.  The Works are wrapped, more or less by our own local manifest authoring, but reference the LOC manifests for any data we can pull from the LOC source.  If the data the app uses is not available in the LOC manifest, we're storing and retrieving that info locally.  

Any questions, let me know and we can also walk through the updated structure if you like.

You can view the updated code in these commits:

https://github.com/adamjarling/loc-speculative-annotations/commit/01e09807c24875743737a464ffe010ca4d42a221

https://github.com/adamjarling/loc-speculative-annotations/commit/ab2daa90bede99c11c2503962d90e54f7942a2e1

**Comment by jaimemears** [comment]
makes total sense. Thank you!
