### ISSUE TITLE
User Feedback reccommendations

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#49]
### Round 1

![image](https://user-images.githubusercontent.com/3020266/110243480-2ddbe980-7f20-11eb-85a1-1a988d7abd5d.png)

### Round 2
![image](https://user-images.githubusercontent.com/3020266/110782369-ab5b6e80-822c-11eb-8b4d-63501d88d9e5.png)

https://docs.google.com/presentation/d/1hJeMcKuolEcsH7x7e2DfpV78Eks9qSQ3i8PZbiC3glA/edit#slide=id.p

**Comment by adamjarling** [comment]
For handling mouse events...

https://stackoverflow.com/questions/44320104/fabricjs-how-to-move-the-selected-object-by-keyboard

**Comment by adamjarling** [comment]
Implementing the following from the **Round 1** list above:

- Delete quote icon, pointer and speech bubble
- Remove all Shape options _except_ for Square and Circle
- Move color selector to top of the Toolbar
- Undo and redo buttons moved to top of the screen and grouped with Zoom in/out buttons
- Move Info button to bottom of sidebar, directly above the "plus" sign control
- Keyboard shortcuts for moving objects and deleting

**Comment by jaimemears** [comment]
Hey would you like me to move the post March 15th stuff into  new issues if they dont already exist?

**Comment by adamjarling** [comment]
@jaimemears That'd be great. Yes please.
