### ISSUE TITLE
Highlighter tool

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#52]
drawing tool added to toolbar with some percentage of transparency

@CourtneyMcClellan could you describe the colors you would like for selection? Is there an icon from the list Adam sent that would be appropriate for this in the tool bar?

**Comment by CourtneyMcClellan** [comment]
@adamjarling Do you need anything else from me for the highlighter. I believe I shared the icon, and highlighter colors. Can I help in any other way?

**Comment by adamjarling** [comment]
@CourtneyMcClellan I'm good here.  This is the next issue I'm going to jump into once I get the IIIF stuff ironed out.  Hopefully in the next 2-3 days.

**Comment by adamjarling** [comment]
Now up and running.

![image](https://user-images.githubusercontent.com/3020266/112727203-55a2e980-8eef-11eb-8a3e-cc8786823251.png)
