### ISSUE TITLE
Implement keyboard shortcuts

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#56]
shortcuts for moving images around, deleting, and selecting multiple to perform an action.

Allow users to use hotkeys:

**DONE**
- Move left/right
- Delete
- Undo/Redo

**TODO:**
- hold down SHIFT to draw out proportionate stamps and shapes
- hold down SHIFT to select multiple elements at once
- copy/paste

UX- Wendy question about accessibility?

**Comment by adamjarling** [comment]
Pulling this work in (partially at least) with #11

**Comment by jaimemears** [comment]
We just dont know about this one. It seems important, but no idea how much time it will take. Is it possible to just implement some shortcuts and not others?  let us know, we are open.

**Comment by jaimemears** [comment]
looks like arrow keys and delete are working so can we close this?

**Comment by adamjarling** [comment]
@jaimemears Yes, if you're happy with current keyboard event handling, I'm good with closing.

**Comment by adamjarling** [comment]
Actually moving this to Backlog in case there's time.

**Comment by jaimemears** [comment]
closing - not mvp and entering final sprint.
