### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#57]
to be completed with text and images

**Comment by CourtneyMcClellan** [comment]
About text can be found here: https://docs.google.com/document/d/1L99-iBvXrf035HFIVGi0Mj-hpwsjFXpywMNXvrq9d7s/edit#heading=h.qfy0ywr9s339

@jaimemears if you want to change the LC Labs title as Sahar suggests, you can do so in this document

**Comment by CourtneyMcClellan** [comment]
Link for the 3 images, captions in the text, where to place the images in the comments: https://drive.google.com/drive/folders/1H35NCoUX4y4D5NinCLIZaWLxxJQcQR7Y?usp=sharing

**Comment by adamjarling** [comment]
Updated and pushing to staging soon.
