### ISSUE TITLE
Teach page

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#58]
to be filled with text and images. Can we embed a carosel or a way to show multiple images easily? Adam after you answer I will assign this ticket to Courtney.

**Comment by adamjarling** [comment]
@jaimemears Is this a separate page from the main "annotate an image" app functionality?

**Comment by adamjarling** [comment]
If we could get a visual, like a wireframe for this that'd be great.

**Comment by jaimemears** [comment]
Ok I will work with Courtney on a wire frame. The page I'm refering to here:
![image](https://user-images.githubusercontent.com/22895272/111467790-3b9d2600-86fb-11eb-9c54-24dcb998f9d1.png)

**Comment by jaimemears** [comment]
We are going to simplify this - text with some images if we can.  adding MVP label.

**Comment by CourtneyMcClellan** [comment]
Text for Teach page: https://docs.google.com/document/d/1heChF4VFDWzbF8_-9MYVhkgsPbKU6zCXHFvV6GqkArE/edit?usp=sharing

Reach out if you have questions!

**Comment by adamjarling** [comment]
Updating now and will push the changes by tonight.
