### ISSUE TITLE
Thumbnail gallery

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#6]
- 2 levels just like mirador 
- gallery view of all possible items and at the item level 
- available for viewing thumbnails of a multi-page document as well as curator overlays.

### Product example
Mirador

### Reference links
https://youtu.be/9KCn-179Dac

**Comment by jaimemears** [comment]
Suggest for language : "Select another item from the Library of Congress"

**Comment by adamjarling** [comment]
This initial functionality is in place, so closing.
