### ISSUE TITLE
Resize text

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#67]
Resizing text-- (sliding bar or + and -)

**Comment by CourtneyMcClellan** [comment]
We are requesting the + and - not the sliding bar

**Comment by adamjarling** [comment]
The text size adjustment would look something like this?
![image](https://user-images.githubusercontent.com/3020266/115956776-616cd600-a4c4-11eb-8c12-460ec442ef38.png)

**Comment by CourtneyMcClellan** [comment]
Ok, this looks good. Just to confirm, no alignment.

**Comment by jaimemears** [comment]
this issue can be closed. creating mvp ticket to set default text size to be smaller.
