### ISSUE TITLE
Remove an object from canvas - refactor

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#68]
Replace trash can with an eraser tool that allow users to select the tool then select elements one-by-one to delete on the canvas.

![image](https://user-images.githubusercontent.com/3020266/112724376-0950ad00-8ee1-11eb-8e0d-48a2acf3b688.png)

**Comment by CourtneyMcClellan** [comment]
Trash can functionality required but no eraser.

**Comment by adamjarling** [comment]
Got it.  Will close this issue.
