### ISSUE TITLE
Text background color

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#69]
Ability to add background to text to make them more visible

**Comment by jaimemears** [comment]
The current default background makes certain text color illegible. Can the default be set to transparent for the text box? no choices, just transparent all the way.

**Comment by adamjarling** [comment]
@jaimemears So after playing around with settings for the Text bounding box tool (which is now live on staging), I reduced the background opacity from `0.5` to `0.2`, when a user is actively typing.   Maybe it's better than fully transparent?   

The reason I left a tiny bit of opacity, is I cannot add the bounding box controls to actively edited text.   So, if a user was editing text (with the new bounding box), with full transparent text background as they're typing, the user would have no idea when or why line breaks are happening.  Which might be confusing?

![image](https://user-images.githubusercontent.com/3020266/117662822-9be19e80-b165-11eb-9551-15bbf94e399a.png)

**Comment by jaimemears** [comment]
Great logic. Just tried with the lightest most troublesome colors and its very readable!

**Comment by adamjarling** [comment]
@jaimemears Or...messing with it, and I could also do transparent background as you wanted, with a white border (instead of the default light blue)?

![image](https://user-images.githubusercontent.com/3020266/117664087-fdeed380-b166-11eb-9055-624384863e61.png)

**Comment by jaimemears** [comment]
Oh yes that seems optimal! Does the white border disappear after they are done with the text box?

**Comment by adamjarling** [comment]
Yea, the white border disappears after user is done editing text.  I'm pushing up the latest changes now, and this white border is included.  If you like it great, and if not no worries we can revert back to the lighter opacity.

**Comment by jaimemears** [comment]
I prefer the white outline and transparent background but defer to @CourtneyMcClellan

**Comment by CourtneyMcClellan** [comment]
Agree

**Comment by adamjarling** [comment]
Great. I'll let one of you do the honors and close this issue.

**Comment by jaimemears** [comment]
The honor, sir, is mine.
