### ISSUE TITLE
Metadata panel

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#7]
Side panel thats collapsible that shows:

- metadata about the item and 
- a link to get to the original

### Product example
Mirador 

### Reference links
https://youtu.be/9KCn-179Dac

### Notes
How can we augment what's available in the api - provenance notes, materials its made from, etc.

**Comment by jaimemears** [comment]
Here's another example - https://labs.loc.gov/work/experiments/loc-3d/cast-lincolns-hand/?st=3d-item

We cribbed this from Smithsonian's "Voyager" app https://github.com/Smithsonian/dpo-voyager

**Comment by jaimemears** [comment]
Instead of pulling directly from the record on the library's site via the API, we may just want to hand code these in because we know we want to add more things and change the language. Fields to start with: Title, Date, Creator, Link, About.

**Comment by jaimemears** [comment]
Is it possible for the text in the metadata panel to be editable by users but for it to be visually obvious what's been edited? (Based on teacher feedback from Smithsonian Learning Lab). This is not at all a priority, it just came up as a user need for teachers.

**Comment by adamjarling** [comment]
@jaimemears I think we can definitely hardcode the data you want displayed in the Metadata panel.  Why don't we start with compiling this information for each source image you want to feature in the app?   You could post the data in this issue, or email me the data, and then I'll plug it into the app.

This could be territory for IIIF, if we wanted to store the information in a IIIF compliant manifest.  Maybe a manifest already exists we could just store locally?

For the second half, of editing info and displaying what's been edited...there's probably a solution for this but it will take time....so if it's a priority, let me know.

**Comment by jaimemears** [comment]
No, that functionality is not a priority.

Would you prefer I make a spreadsheet for this with each column representing a metadata field? I can start by creating the metadata for the four images we are currently hosting so we can see what it looks like.

**Comment by adamjarling** [comment]
@jaimemears That sounds like a great place to store the metadata info for now.  Yes, please do.

**Comment by jaimemears** [comment]
Here is a link to the spreadsheet i made with metadata for the four items.  https://docs.google.com/spreadsheets/d/12Iq5AS0yb91KmpvMI-OwVpIn5__HQwH6eCjuH93imoY/edit#gid=0

**Comment by adamjarling** [comment]
@jessvu, where do you think the "Show metadata panel" button/icon/control should go in the App layout?

![image](https://user-images.githubusercontent.com/3020266/108504781-104e2500-727c-11eb-9cda-07d3f6df9122.png)

**Comment by jaimemears** [comment]
I was thinking it should go in the tool bar - maybe with an icon such as an “i” with a circle around it for “information”?

Sent from my iPad

On Feb 19, 2021, at 7:32 AM, Adam J. Arling <notifications@github.com> wrote:

﻿

@jessvu<https://github.com/jessvu>, where do you think the "Show metadata panel" button/icon/control should go in the App layout?

[image]<https://user-images.githubusercontent.com/3020266/108504781-104e2500-727c-11eb-9cda-07d3f6df9122.png>

**Comment by adamjarling** [comment]
@jaimemears Pushing up some changes now... Let me know what you think on display/ordering/what-not.

![image](https://user-images.githubusercontent.com/3020266/108720055-f3b52580-74e5-11eb-905b-5ebd5e878b40.png)

**Comment by adamjarling** [comment]
@jessvu giving feedback on where to put the "info" button control.

**Comment by adamjarling** [comment]
Closing as the panel is now in place.  We can always move the "info" icon control to another place.
