### ISSUE TITLE
SA and LOC logo added to the download png

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#71]
Jess will upload the mockup for scale and location of logos in Slack

**Comment by jaimemears** [comment]
May need to be combined with issue #20 as part of the design layer.

**Comment by adamjarling** [comment]
I think this would be nice branding to have the logos continually present, and would also save extra work of adding the logos to the download feature.

**Comment by jaimemears** [comment]
I am assigning this to myself so I can get Jess the bw LC logo. We also would like mockups of including the hashtag #annotateLOC on the canvas with the logos. Could we see the hashtag in the lime green in courier prime as an option?

**Comment by CourtneyMcClellan** [comment]
New small addition to the canvas: Along with adding the 2 logos, I would also like to add a "Name:" to create a space for attribution for annotators. I will create a small mockup and share. Certainly use your expertise in thinking about placement. Part of the thinking is that I would want the attribution or lack there of to be visible on anything on social media (so thinking about instagram format). @jessvu

**Comment by CourtneyMcClellan** [comment]
![Example of name](https://user-images.githubusercontent.com/77364108/115282512-4abb2d80-a118-11eb-97b0-366bf94f1d8b.png)

**Comment by CourtneyMcClellan** [comment]
@jessvu can you attach the mockup of the canvas with the name and logo blocked off? Will you pin it here? I think we will need this before curator annotations are added.

**Comment by adamjarling** [comment]
Closing as this looks duplicated by https://github.com/adamjarling/loc-speculative-annotations/issues/71
