### ISSUE TITLE
Provide curator annotations for select items

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#75]
The easiest way to accomplish this (at the moment), would be to click on the "Shareable link" menu option pictured in the screenshot below.  Copy this code and maybe email @jaimemears or myself the code? 

I'll need to take this code, decompress the Fabric JS objects and then save the JSON data into a work's local IIIF manifest under the curator annotation area.  

![image](https://user-images.githubusercontent.com/3020266/114271653-091fd980-99d8-11eb-965b-c37a2d1f2d57.png)

**Comment by CourtneyMcClellan** [comment]
@adamjarling Let's test putting a curator annotation into the tool. Below is my annotation for a trial run: 

https://nervous-gates-006218.netlify.app/78694920?sharedCanvas=XQAAAAL6PgAAAAAAAABBKcrGU8hqLFnqZuoRloe2ifFZ9nH7RDdtEytgo4hdbZywSf-CyF0qlGy2tzDAMFS0M2B3aX4_jVEEPs95wHTzW5ot4kbuEu7wBsESr6BzHfJW5JXtPu8wwXwNBkbNMLcnZHQkYXDxa2p1NuOcYjAnxRLeJ8E4BBCUiDV-MaLiYiq0tXwTtRcYlGpsZBpA9_OB7xDKwrG4wLJz5AVB4noqLzEqp5CFPsAtDt6TqD4bB6XtRaqznbLxgujcQzC2em9ikRS7Ayvq2Kj3OURcE8xi-H3oRMV9-q9-zMa8vUh08Eogh6vjyb49pzyuW4X8qkECBa1wgLRPlpjMRwUJAeM_m8l09VABJLd23MGjhh9aaKnyOYUkbWnafYcqJQdRs-20eW7AoDpVfqen1Ni3_JTsr1WfmyhCbag8ThSS6rkNpNSqCW7Qml9qCa87EDo2kFIVVxj47QbjMLCkjlNTfnOUPwVq2leEjvwqIeAh7jpL6vKUceooIJABrGo6J-k2ZNzo-kUi14Np5BuR0BcJk9yu2CiC9kn0nhMMKAW0M55OZi215ArUVNZC7wFVpNur3Yx1182P7trhNla9vUttTu4jj-2gj7eSJX5J8nZboNeme8IWZlehL0mBE5R4MgJ1U0RurHkvmsGSXt8XKYQabl3CmKiXjeVK7H-Dhpk8HCdOye8AL2_N72-mG0m4fQGuaatfmwz-KsnzDFGAnW5Df91aXTKJJqkFDkq_5_6r4nA_kxGYvCFTDZb8jkl6goHU1xA6zoXGEO_FO-qKFgzjT8lOS1XGzt3QJN2d6S_Q4nIj-tOfUEEHv_nohpNYgW-OB57Y4Vscq0YN0fyRpoFJmVgYTSnb1kmalHxBrGIYsTBXdQnqAYJKscxuzwqhnVRpfJQXwlwoA3JqEGbZhfb71k3aSX-788l9zO07OAR4hmaUrEF_bfFu061h3qV7NqGhG3AS5xZVC4wjPXwsasloD1xDv9Zqf4PJgFzvpyy0S_L4Q7-c_PqK86JY-jicZp1DzZFZzxgKinQiOUuMg_oElJSYTwCFm82gTOpKe9h626ZFyRFz8jb5SweHSoT8zOYyzqvUmrWtU_gDzkEfXhG_AfwNT9AzNuD9IJNdXeMkwiwSA0BZrEtAHht7KrsjRtoUs3FzNyOTyGtnzCojv1J7Ab28ubLilhDuFTsPpEEcjOuirrcFkSCciT-fLF9LzEbRDMdmrVRkNpDf5Px3_byH5H1KQQSxRxjGOI1copuBFelm7bttuIj7xmdR0BEbQb5SgrIJuslWb7TAzuxYFJaW7q1DFbALIppYAkuJ7eQsVdP7kpnLxhV9zeCb11GJami8FtSZZRCxqICGu2wGLsSEDNNGDS8y2GC_DvczFy0gF1P5ejQsXad8Qocq5LsR_29-azPkGGXrWj5xq6dUTIQuF0_1R1egk6FABozqAObxiVBcQSgbE0swqwZU3_xW0SJCKw7uiyOvbCC1SoGz0Bo-XTB7EEDskPZmkkp3PgT4PeIMqflulVEYzf80-5te747rUjBpOrRkOHatRDE7s32ssoA_yd3Zx5n_8v3peo3S0ywjANvAn7Pub8vszsizPI_SgzK9xzUrNiQQ-Plty_-GFSG4UL7uxjircewS2-PXsw3QRTXOkbjTNAvriHK-GzQyc6JwVHmcBgU6sKfJ8_4TixJGQvAd-f6RfXq6uAGSgMk8zGj1LlofsEiRskbvReWRanB7T53s6gYQNsbm4b5U27-IlNPkD5vYLxTjZOhgmHvqkzM6LcHFrVW4fdNe8M0rUnBp4-TUoKTntt8OeMO4fcy-gmTHurEyqC_xhFM5X6vVpe8mHJncsYXRHHFUD_YeB90y_otOccz-sSYSRMKFMLbRGxGiLNec8dQX_AU4SovIcLV8pieojA7UWR8QDgv5xZrPA5KUrpMQpAKmzhVN47QHHbKRWjjwXKQ4I3JXfvYfm96wjJ2rOX0e30RKZALmz03wUKWC1racsIC5q0k2CwJtPBfbZSvOd100QTsnWMV0M44JVLpq95e7hAzpQLZjWjYm-S8uRzPdJuZTe-_jP8IMWvUbiCnbAFRTDB39HlGNq5XlbVOH_U-rmXUEJ0WNINePnh3-WWdk296Ju7ncFg7qMG5lEf2Ca5J2bbdp0-EL_vCwL4SsN-SS_qGwaAaLPbfcoM258wTLVtFQRoFX7rMmEtJ7lDfsCPasrhZ_2hDQiH7LfUv_k4VA6t1XEaZPUVs59TMhxX01dfoJ0nEWlGxaGKD6KDpyNbzcSKdSiJDGFehzvx3cmxtnr0fIcCYf3EpwgORdKJKII2GvncBW1sU0Cte91egrw8kGtGWkLTu36qtTobIh04C5Wv9th9Wl2zvnAOdFgyEQLkiXayiV-OcZboKTc7VCDT1-958LTJ1G6AMVNujrfU-4EZLPsjq07JlmLxFj9Znx9jkDiVv_akteNB2LLQi0OQ6Xcwvr1rMyRWaGCIh6GOGUgd9B1I2DAsRsxc3oXcsJjvxn3hg8hI8ZxhldkLgDXEu1vMoUBnzzmbrpI3BxeN6lrdm8ZCbwBZsJMIJ9Vm1uUX6eQ5lSEWvamUiWUBJx5M3ID71tLyCYWqDNelgo0xR4Hs-jmqTmFjxrfOdP-BoVinwkzcKsq5HCRLFSkbkGigBMexBBHLHt3ztuUBG0YxsUW7SzLl1cAAQC_7DJJMi-h9WUhjUJJna8yMrLiYkKcRtJYWUMnGozwnNKmXsvXSM7qUPaqfVfPDxrg8-jw-J5rGQeirrgdM9LWlyByy0hBrb9kX0mx5WUaFeJmKl8rPeY5Qf-pZBJ5PYTWVsBdpuH7W2X6CpFwER2s-wSNIMkqzeujLoZ5XBtQT0kBuYyV9tdMn-kNd8tYBBQj1zJ5KMnHSUajaVasku-anLpvjQ_ud99BGwIexfML5TrwBaR-F_jHeA0j4tBq2W-9WaouoJ6GoBR9qabTDBN4bQSRMDRb9XEWlCTCyDliyJ7FPCNcIBFqFHcMbspyMs0fGuYzn3xAxYifLdiaI29eVvL95z98sEZA9YSoltvYhKbp7atCzPPlWfoRlxQ8s2iSUchmzFRqzFI3RvsBJdP0gzBUeYFmrkaiVi7JLujkvlZOisXlVu-zaKphW_WB8iVGgswtlNyPq1CfS0NFmvVWV-jDNf90LiaC25eK7ffOklo__fjmLLzjK0BzFuMYuMBPA8s_QmA-CaeHO4wQodFn7uYWHX8KVBHPhw34TojtIOrLMItKWr1OEEhiMC0nSbNPjF4lfQiZK5QarU6UDf9AqknIArVn_xHOB9aJ10xu3JZVf5XUoQzkavzEIrZKZMPllTo3uawoaxvsPbDgVGZgCVJ30cePTNquGU9AoH_5OowkL7uLd0mjDywuthor_qnB2LWCSp8zCXU1_ZdRlgQFijCLS0Myzf_305QqO3y1LPWf7gd-kikD293rAQjr5LwDxb4c-nU1OuspnnxwNy0x1Mpj_GX52osSPYDScxPIWjrgW1DOq0GHqNkJom86ptYrSI2NJMkJ8bg252OgKJdedAeNV5e6x2fdr1l1tVZZuPna15ySbk57a52s_DV8bU7ecbXX0fPoOpy4Ug5OHIvIgFG7OECZewzkDLLcaMeB6DYzlqZGKnvOYy-q0UIP8hmGKMs_5IJ4U_5NuYH1kio3hI8x3YLibG4puxfGDLv-pFe0NpT3WMJV2scTWmyqHtch9zcfXPc1Jdpr7AJVkB_T3FfQsRjmGH5ZEJUMT7fysSQbIfvT3PrzwQJMWhf7zxUEVTqfxCA4gZcdunWWEk2ckUhkVyCZv8kvALMbrng0EM3gShbUmUHwTMjhAG9QuEc42n6AN7GnQ0rWNqo6qdVU-KVcx02cipfdYizPxrFRW7PRVxNmwvWQiWo3luJSFjUvXqJPaaQS0exdomIORpbTR8F9cC7CcZT1UZoIKalTbiPBFB7aJXXd9ovskyrXmw7Y4zjUyrKKH-xZlnTtM0KjlRl-Cr2IdHhsZMkGCXPGHmko_rtx3uwNfUGXBuaMgx2H7mxiSGDFR4VDDpYv3ZDrCTOuPczsiW3WeEqgCgoE4wng11tSYKJp7vHYvCAwVzHIa8GO0Xs540b8RDyOCZypL3Gnau-bvq3qt3s1fXqVgSABcUn8kDWOY8U_kOsjbgf-aRW0U893qTo_1ydxg9JhlwAo34RsDDsVzFmH82STsvzPyk0YCbLiHAckgeFDVZIGwyi3_E6ni2DqbFlyWmn7MKr1or0DZ0p3Pttm_AoEigHwiLlhb3VqV9zk_H0oXYNqBN91fF-4h19pwrvKhhQP3knC6EVvA-_9pCnh__qK_S0O2MLSC2VN8pPE3FGDqYIgSUe3tk2ENpsJzL79MDwKy2h-92d98rIK5co0IAM3yrlZpIwU_Ug-f38VqB4qH2OXrZL-jQ7vo6F1Kpk495a7qEXVwGPcAD1iIczgRisfTBlWUe1YSbDM9Fr2gPSQNvNxnxDwTPO1kVQA8vQ6IFqlfMXHDfMvTrdizW84uXnOskiuVFAaOjAT_bi1gaR-BVt2z6wO6w-Mgwfkpxd2Gc_DPVaISNPCX3LepO_Alfu-2NZPg0nIrZkStL_DWaL4d6x8geqzE2QtbfFyypjDJnulNTOjDiuk-EKZVojYylbkgCbwadFVvFULTyqgiLUzDKBrEWcnLEz3rp-_AWbO_SBIVuP8OVHaavp5P4wxyBFVarBt0mGd6L1r3XkN-u_9U5uws-mv36MvhC3SwMNMLvfto3_eS6udSE7FdaqXgGMe_FACUza-sIVvy_68S-jScByocaicVlRsDvinuq-h6JUjnArS8syEX1p6oQhFWdznSE0MGPtyOA41rgV7RW1tfPzHBZaoEEpV_SC8O3ccb5qvmJZvdLZOL_Zvb8kzaQ65A_bpMJR_vhpXR4eOGbiwsVE1js2C61MBXM2sVbSw7nzQA-7WQ0lRO46scvnUNhlNzC6QqZ6QiTbclcIfk7uj9-83RUoXluGUtBW4Fw69H_K2SYaJ8Hf6iXzL2w1IIgkKJdTJq4PfCpdk37GRtRuOcyJA4ITlQf3pGqVdsDdS10-18XIehgmt_dHM7oA7zTt9hma9kTK2DWLv1P9dEmeeW_8AKX5dv5NJnNaOM2Bv6HMOWaEmMZQHWUYNUI7_lTHmi0KlHfiAlPACve8dqqOqSGf-6Mcid0WC7cd-uySgch46Ozb79KznFkd9duRvoVyRf6vy3oUSpDDm-QuBTi9johsDxcQ8HCS9krtvl3uZSkkKJYaKQClH-ch2-eRY7d5h8oS0Jw2fZXElYakJyJcNX5OYbX2MA-A4H9EYpWBI59bgYefwDsV0DxYSbDG631DraDbXE0Z3hnqh7Yi9nDk1XElxVPjgIgaS7aOAKcfybc1-b6H48HR7bXNmZ1czlQoIvm2MecPr9bAOHG9nOJ7ZKIyFJaDCOvIv5B_Vl51uA7RA0U_qwe93C361jEJwBcmMLyR5hhVAlRC9DC1rpYWBl3-giDrqjvUxE6mpZvHOi10chQB4XxbKjsTGWcVPACPTMiJEVAGALTJUb2-COE8dEoyGGc3tPBkv4ocTzqbB3CkH52dDJaH1qnliuAIaubLqODtWNaup-kp19VbM93XxDTTH4zlss_6Dloy6fQStDCxxhM6n2ZLhN6CJo7jXGbE200cLFEHBLPbYFwglecn6kHXhKP_39ks8rNn_TCHiuUm4LEDuC0GfDuiZYkLrhslSlcUIRMCBaoq0GShUNglgFjJ0CQg_LrvjkAyXafiv-5BXlCCPKzOHV3QMMGWIKUrQwN_2GV-zT51GcpaxiIqLBuKDbvdFukK7bNBxG8O6v3rZeS-ui7B_RdAABAoCHvMnlnt6WeN_X43cpmgkB6n8SloH964JSeldV3rEkhtA2ak9pWkQp-j-giJUYuXvd_UJ5VeplKr4bZ5HJD1xb6l0bkF1lXqVAr6CZ6ljcATL0D3vt1qmLl6sBolfCMpKK9ijlf0dji2DPeEo4nKRsRvXKNODwl-YD7p24lm_9oqD3rygPaDntmWerGQtb3jLLi7iCMu7ylSchG05J_fTnsh_LO573gMu2Fpct9vZRWTpSUjGXjVpZZPIODU9Q0jxINL2I8nQR1R3jT42FX0PfocGi5xNuFre0NDdNvEKC35mkNtiMSnApwh4no1ryZm3IZ0rK3MT7VtcLgCmotnSpI16Oo4to_8nKkfGl4IImeYECqrAfGSRZw62b4wqmc5CxS_kIbWknCIEpsUOpK9EUyUzsRg9xxCvwQJQTPledQFpbaHw3n35H8RijpNsqEiiuOvkVJYU5DkXV16CYiJ94eKTnU03rd0mrqIEI2gpl9_WzktQ537NN-NZDYm7CplmBFinFupsID2JI-2nM1a5l5R9ADN0vzNNuf3aKVDCEx8NCCm9EswpW57Snoe5wzjJ10BsvFkvolkYAWo6LvN8ECDXLbt5eKfeWTnOIDgDoMSO1sDsOuEG53ZQ7uVeUGjHk7sL879JvHpIcPLEnL8NrlfD6FRUto4gf0Ab03sPH2w-8Ze00JBdIcEltTzE91sgL_-sfgiX-I8S9LQO2ajbPHXcMDrjKuO_ps1tFQ8h_yfZF0s4eKzt8dBrj-eyTldrCrjrhSIMplhWypZOaXzp9cKAVjMcnx1zrYW37NY4ypVL_zQNLbT9qATZ7-Ltx8_Q9IZuIS05NtwaRR2JDuPm2tKtuKw1pwfex0pvAU_uASUmL7LD6VYch3APfCc5vfI4htQWQYY4MmsNUWkUopsHS7Iryd4QA8oKmEGVnCyEHSM0cYkbY8rQelJV4x0BKXzKLhO__O7DoUu9AqFCPMTOPVHY2he8XgKqNY8mAb3ZlnSsKxIJOhe1ZtDegPUeiWFo38_4nhxToZYad-ZKHc8B1H9QHw753Mpdoa-Xh7r3Hpj8kxUZ4HKkI85WJY8DX6N250Rjjcv3fZ66sII44bhMiAuIBGtS6iEtf_4FSHH

**Comment by adamjarling** [comment]
@CourtneyMcClellan When clicking on the link above, I see this... does this look as expected or is the sizing off?

![image](https://user-images.githubusercontent.com/3020266/118268165-a7450a80-b482-11eb-8ff6-8bdc6649b5aa.png)

**Comment by adamjarling** [comment]
I think I know the answer to the above question, and this brings up an issue we'll need to consider:  LOC Staff (or anyone for that matter) will be saving annotations to a given viewport size.  When sharing annotations like this, there is no way to ensure or assume another user will be viewing on the same viewport size.  

Zooming keeps the scale in sync, because it's controlled by the app, and that's the way that the Fabric canvas is "pinned" to the OSD canvas underneath.   But resizing a viewport is different, and the behavior of this tool has always been that resizing a window will displace your current annotations.  

In order to make this work, we'll need to think of a solution.   Off the top of my head here are a few ideas:

**1. I think the easiest approach:**
We keep current app functionality as-is more or less, and save PNG files of LOC Staff annotations to accurately capture their annotations (instead of Fabric JS object).  Staff could use the existing "Download" button to save annotations.  Then we store these images in the app and toggle the display of the curator annotation image somehow in the UI.

**2. We still try and transfer the FabricJS object and recreate it on the app canvas**
- We'll need to immediately start capturing the canvas size when LOC Staff is sharing their annotations.  This is the only (I think) reliable way to re-create what they were seeing.
- From here, I'd need to figure out a solution for how to scale Fabric JS objects to resized viewports.

I'll start looking into how to scale Fabric JS objects to viewport resizing and get a feel for how complex this will be.

**Comment by adamjarling** [comment]
Or, we don't allow OSD to resize it's image on viewport resizing...

**Comment by adamjarling** [comment]
As an update, I'm having little luck retaining a collection of Fabric JS annotation dimensions relative to the OpenSeadragon canvas.   If it's acceptable, finding some type of solution along the lines of #1 at this stage in the game probably makes the most sense?

I'll come back at the work of trying to sync the 2 packages together (Fabric JS and OpenSeadragon) on horizontal viewport re-sizing, later tonight but as of this morning no decent progress or leads have surfaced.

**Comment by adamjarling** [comment]
@jaimemears @CourtneyMcClellan I'm about to push up code which tests out displaying a saved Curator Annotation PNG file for the following work, in a new browser tab.   Let me know if the zoom level on the new tab is ok, or whether you'd like me to wrap this in a deep zoom viewer to give better control over zooming/panning and so forth.

![image](https://user-images.githubusercontent.com/3020266/118580053-cbd80580-b754-11eb-969f-57ad9e21e3f6.png)

**Comment by CourtneyMcClellan** [comment]
This looks great! Jaime and I took a look today, we think this is going to work well. Jess is working on some layout mockups.

**Comment by CourtneyMcClellan** [comment]
@adamjarling Curator annotation files are here: https://drive.google.com/file/d/13SvN2k3wuLOu33VHSvRkD0QrDPeMUePS/view?usp=sharing

Feel free to reach out to me if questions arise

**Comment by adamjarling** [comment]
@CourtneyMcClellan The link above only points to one file.  Did you mean to link to a folder of all items?

**Comment by CourtneyMcClellan** [comment]
https://drive.google.com/drive/folders/1O3DspM_5svagM83i6XzzENNtSxuipK6l?usp=sharing

**Comment by adamjarling** [comment]
All these are now added to the app.  Will let you review and close if all looks good.

**Comment by CourtneyMcClellan** [comment]
@adamjarling we have 3 curator annotation files that need updating. They can be found here: https://drive.google.com/drive/folders/1vnSMsiXIbAOHgxDbqqmqWSnPfJQG8g2H?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan Images in Google Drive link above updated and pushing to staging now.

**Comment by jaimemears** [comment]
This is good. closing.
