### ISSUE TITLE
Textbox update

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#78]
From UX feedback April 8, 2021

![UX Review of Features (4)](https://user-images.githubusercontent.com/3020266/114271961-9dd70700-99d9-11eb-8070-54e29439663c.jpeg)

**Comment by adamjarling** [comment]
@jessvu Ok, I think I understand this from the attached video.  Question, would this behavior change if we don't have time to implement a font re-sizing control in the adjustment bar?

**Comment by jessvu** [comment]
If we don't have time to implement the font re-sizing control, I think we should keep the ability to drag in-out with the corner anchors to adjust size if possible

**Comment by adamjarling** [comment]
Ok, I'll keep this issue open but just push it back to make sure we get the other stuff completed first.

**Comment by jaimemears** [comment]
Courtney agrees that the font re-sizing is a low priority "nice to have" @CourtneyMcClellan

**Comment by CourtneyMcClellan** [comment]
@jaimemears and I are both having issues with moving/adjusting text. We think this is very important to the functionality of the tool in order to annotate items for users but also for the upcoming user annotation. I have attached a video showing my difficulty in selecting and moving the text. 
https://user-images.githubusercontent.com/77364108/117197258-9a0a8a80-adb5-11eb-8099-61fcd0bb261a.mov


https://user-images.githubusercontent.com/77364108/117197258-9a0a8a80-adb5-11eb-8099-61fcd0bb261a.mov

**Comment by adamjarling** [comment]
@CourtneyMcClellan So this is related either in part or in full to this issue, which was at the top of the "To do" column over the weekend.   I pitched a question on it, but never heard back.

https://github.com/adamjarling/loc-speculative-annotations/issues/65https://github.com/adamjarling/loc-speculative-annotations/issues/65

One thing I can try and refine is to allow the type tool to type on top of existing non-text objects.  But if hovering over a "type" object, don't allow a new typing to happen?   

Or, I just pull back the behavior I implemented over the weekend and don't allow typing on top of any previously added objects (which is what I've seen in a few comparable annotation apps).

**Comment by CourtneyMcClellan** [comment]
Sorry I missed the question. Jaime and I think to pull back the behavior
you implemented this weekend. I think this will make the curator
annotations much easier.

A further question: The motivations for this layering is the use case:
typing over a thought bubble. Is there a way to distinguish layering text
with text  or text with stamp? Does the canvas see them as the same thing?

**Comment by adamjarling** [comment]
Ah, gotcha.  I can double check, but I believe we can only distinguish between the type of FabricJS object.  Ie. an "ellipse", "square", "text", "line", etc.  Speech bubbles would fall under the category of "SVG" or "image" I think, so trying to build logic into typing on top of something, would include Stamps and Speech bubbles.   I can test this out and let you know what the possibilities are.

**Comment by CourtneyMcClellan** [comment]
Ok, cool. That would be awesome, thank you.

**Comment by adamjarling** [comment]
@CourtneyMcClellan Playing around with this event behavior this morning and trying to wrap my head around things.  So is the motivation here to type over a StampQuestion (the new images), or to type on top of an existing Stamp, which happens to be a Speech Bubble type Stamp shape?

**Comment by CourtneyMcClellan** [comment]
Type on top of an existing stamp like a thought bubble.

**Comment by adamjarling** [comment]
@CourtneyMcClellan Gotcha.  Well, seems like I can identify certain objects (like a Stamp, or the new Speech Bubble Stamps), which will allow text to be typed upon.    If this functionality works out, would the new Speech Bubble Stamps go away, and we just use existing Stamp shapes that are speech bubbles?

**Comment by adamjarling** [comment]
![image](https://user-images.githubusercontent.com/3020266/117308507-3630a200-ae47-11eb-99e7-9bb9f56939db.png)

**Comment by CourtneyMcClellan** [comment]
No, the quick questions would stay. The goal would be that typing on the
stamp while removing the need to layer other items. We had difficulty using
the text tool because it was hard to pick up the box because the cursor
kept starting a new text.

**Comment by adamjarling** [comment]
Ok.  For now I'm pushing up changes to staging which revert the previous update allowing text to be typed on top of any object on the canvas.   So for the time being, a user cannot type on top of an existing object, until we get the functionality ironed out.

**Comment by CourtneyMcClellan** [comment]
Great, that makes sense.

**Comment by jessvu** [comment]
@CourtneyMcClellan @jaimemears wondering what your thoughts are on making the ability to wrap text a higher priority issue. I noticed from user-testing that users tend to write a lot while annotating so allowing the ability to wrap text would improve their experience and allow them to annotate faster. I see this feature as particularly useful to those trying to fit several lines of text inside of a stamp area, e.g. writing dialogue inside of a speech bubble. Here is an example of what that functionality might look like: https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gcede5aee13_0_43

**Comment by adamjarling** [comment]
Hey @jessvu I actually just pushed up some changes yesterday for typing in a bounding box.  You can see comments here:

https://github.com/adamjarling/loc-speculative-annotations/issues/66

Also, if you're curious as to what I'm working on as we enter the home stretch of prioritizing given my somewhat limited balance of time, I'm trying to keep the project board accurate with issues I'm moving through:

https://github.com/adamjarling/loc-speculative-annotations/projects/1

**Comment by jaimemears** [comment]
@CourtneyMcClellan is the text tool good now? It seems greatly greatly improved with @adamjarling latest changes. If so, I will close this issue.

**Comment by jaimemears** [comment]
this is great. closing.
