### ISSUE TITLE
Add line and arrow back under shape options

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#80]
Add line and arrow back under shape options.

@CourtneyMcClellan Can you confirm whether you want both line and arrow added back to Shape tool?   Seems like there's a little back and forth.

**Comment by CourtneyMcClellan** [comment]
I don't want to add the arrow back in--this can be closed

**Comment by CourtneyMcClellan** [comment]
No line and arrow
