### ISSUE TITLE
Allow users to make adjustments to elements already placed

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#81]
For example, when a user selects an element they've already placed on the canvas such as a piece of text or stamp, reveal the adjustment panel for that element and allow users to change color, weight, etc while that item is selected.

**Comment by CourtneyMcClellan** [comment]
Jaime and I think this issue can be closed, it isn't a priority with the time we have left.

**Comment by jessvu** [comment]
@adamjarling @CourtneyMcClellan if we close this issue, I think it would be best to not pull up the adjustment panel when a user clicks an element on the canvas so that they are not mislead into think they can making adjustments.

**Comment by CourtneyMcClellan** [comment]
Agreed, thanks Jess!

**Comment by adamjarling** [comment]
Got it. Will update the UI to not display the adjustment options on object selection.

**Comment by adamjarling** [comment]
This is updated and will be part of the next push to staging.

**Comment by jaimemears** [comment]
Can I close this @adamjarling ?

**Comment by adamjarling** [comment]
Yes, close away @jaimemears
