### ISSUE TITLE
New layout design updates

### ISSUE THREAD

**Issue by adamjarling** [adamjarling/loc-speculative-annotations#83]
Make design updates per @jessvu latest recommendations and styles at:

https://www.figma.com/file/laNqMbfi7FSeHweqgyH8Jn/Speculative-Annotation-Style-Guide?node-id=0%3A1

**Comment by jessvu** [comment]
If there is time could you try to closely aligning spacing and size to what I have in my mockups? Particularly with making the toolbars skinnier to create more space for the canvas area. I would prioritize anything functionality-related first over this.

**Comment by CourtneyMcClellan** [comment]
Some new updates: 
- add SA logo to canvas (not going to include LOC logo for now)
- add more padding at top and bottom of item on dark blue canvas (can cut back on gray at bottom)
- move the zoom in out button to outside of the canvas, perhaps in the gray to the right of the current location
- add the following to canvas @jessvu I am going to leave it up to you to consider the best location 
Name:
Age:
Town: 

Added notes: @adamjarling  no tape in corners, this design work to remind visitors they are not writing on original item is provided in many other ways

**Comment by adamjarling** [comment]
Just updated the Zoom controls to match the new UX recommendations, and added some more margin to the Viewer section. 

And the tape Curator feature has been removed.

@jessvu Mind posting a screenshot of where the SA logo should now go?  I remember seeing it in passing, but can't seem to locate it now.

**Comment by jaimemears** [comment]
- Delete 100 between + and - because it is not responsive
- delete LC logo and add disclaimer to canvas underneath image

**Comment by adamjarling** [comment]
@jaimemears Clicking on the "100" between + and - will essentially reset the Zoom state to it's original (ie. 100%).  I'm fine with removing it still, but just clarifying what it currently does.

And delete this LOC logo?   

![image](https://user-images.githubusercontent.com/3020266/118265113-57fcdb00-b47e-11eb-9e4b-e21ea930c599.png)

And what is the "disclaimer"?

**Comment by CourtneyMcClellan** [comment]
Ok, updates/clarifications:

leave the 100
remove the logo

Add the text below the item that is listed here below the item: (ignore the
location of the logo here and the nametag)
[image: original item text .png]

**Comment by adamjarling** [comment]
@CourtneyMcClellan I can't view the disclaimer text image (if you included one).   Could you copy and paste the disclaimer text to this issue?

**Comment by CourtneyMcClellan** [comment]
Yes, see below:

The original item can be found at the Library of Congress

**Comment by adamjarling** [comment]
@jessvu @CourtneyMcClellan Quick question on layout.  Do we want to display the SA logo in the header now that it's in the Viewer?

![image](https://user-images.githubusercontent.com/3020266/118640234-598c1300-b79e-11eb-944a-8bdd377881e6.png)

**Comment by CourtneyMcClellan** [comment]
Delete that header logo. We are working on a comprehensive layout update to
confirm these changes with.

**Comment by jaimemears** [comment]
See ticket #131 1. Closing this.
