### ISSUE TITLE
Change out the Colors in the tool color palette

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#84]
New Hex Codes: 
003366
00F700
FFED00
45FCBA
ED00D1
BAF1E2
A7E0F6
D7CBF6

F05129*

*Additional request (which I can elaborate on further on Thurs): 
We are planning for the curator annotations to all be done in rust orange (Library logo colors). This would be a color we would add for now (by Sun April 18) to allow the curators to create annotations. Then we will want to remove the color before launch. @adamjarling Do you see any issues with this? We also know that the associated gooey (sp?) button will need to be added as well.

**Comment by adamjarling** [comment]
This is now implemented (not yet pushed to staging) and just waiting on updated Draw Small, Medium and Large svg icon files.

**Comment by CourtneyMcClellan** [comment]
I am not seeing the Navy 003366 added to the color palette @adamjarling

**Comment by adamjarling** [comment]
@CourtneyMcClellan Ooops, missed that.  Pushing up the color fix now.

![image](https://user-images.githubusercontent.com/3020266/115560268-08a9fd00-a27a-11eb-82cf-2e3e08cd115c.png)

**Comment by CourtneyMcClellan** [comment]
@adamjarling these colors seem off.  am wondering if they are in CMYK rather than RGB. Or is there something else altering the color?
This is what they should look like:
![what SA palette colors should look like](https://user-images.githubusercontent.com/77364108/116326608-df660100-a792-11eb-8b0b-35f06bf6d8f1.png)

**Comment by adamjarling** [comment]
@CourtneyMcClellan This may have been due to the palette range I defined for the app's colors (per the recommendation of the UI component Library we're using).  I just replaced the Hex color values with the exact values noted above in this ticket.  So they should be exact now in the app.   Let me know if any better?

**Comment by CourtneyMcClellan** [comment]
Yes, it looks much better! Thank you!
