### ISSUE TITLE
Shape/Stamp Functionality

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#85]
![image](https://user-images.githubusercontent.com/32075716/114951375-991fb200-9e22-11eb-9319-6317744e1ef6.png)
https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gcede5aee13_0_26

**Comment by CourtneyMcClellan** [comment]
Do not add straight line or arrow back into shapes

**Comment by adamjarling** [comment]
Unless there's new functionality for how Shapes and Stamps are added to the Fabric, this one should be done.

**Comment by jessvu** [comment]
@adamjarling Could you update the functionality so that a new stamp or shape _isn't_ placed on click? So a new stamp/shape can only be made if the user clicks and drags it out.

**Comment by jessvu** [comment]
I am also noticing that the stamps are getting dragged out even when I'm not holding down my mouse. It feels very unexpected and abrupt - I'm sure this is just a bug, but could we make it so that they only get dragged on on click-hold-drag?

**Comment by adamjarling** [comment]
Ok, I'll try and update the Stamp and Shape tool to reflect the above.  Stamps/Shapes getting dragged out when not click dragging is indeed a bug which only (for now) surfaces in the Staging environment.  It's a timing thing with how the `mousedown` event is handled.  I tried one workaround, but maybe it's not holding.  Will re-visit this weekend.

**Comment by adamjarling** [comment]
@jessvu @CourtneyMcClellan This seems to be working ok for me now...granted there's a slight delay when drag-sizing the stamp.   The buggy behavior which existed previously where the stamp would resize when not mousedown, I can't re-create that now which means my previous fix still hopefully is keeping the timing in line.  

If either of you are seeing buggy behavior with this, please let me know in this issue?

**Comment by CourtneyMcClellan** [comment]
Can we close this issue?

**Comment by adamjarling** [comment]
Yes, I think we close this and if any new bugs surface we create a new issue to address.
