### ISSUE TITLE
Align Stroke Weights to Stroke Icons

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#86]
![image](https://user-images.githubusercontent.com/32075716/114951594-b9e80780-9e22-11eb-84d5-907e446b4315.png)
https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gcede5aee13_0_26

**Comment by adamjarling** [comment]
I've done some work on this, but now seems the values will need to be pinned to 2 things:

- Responsive viewport
- Dimension of the new editable Canvas area

I think we get the canvas dimensions ironed out for each viewport, then come back at this.

**Comment by jessvu** [comment]
@adamjarling will be working on this week and get back to you with dimensions by the end of the week.

**Comment by CourtneyMcClellan** [comment]
This functionality is working to our satisfaction, should this issue be closed?

**Comment by adamjarling** [comment]
Yea, if you're ok with this @CourtneyMcClellan please close the issue.

**Comment by CourtneyMcClellan** [comment]
Yes, this works for me
