### ISSUE TITLE
update icons - shape tool and highlighter tool icons and placement

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#87]
icon for shapes should be updated to just square and circle.

Icon for highlighter tool should be the one with the highlighter and line and should be moved up to be underneath marker icon..

See attachment image.

![image](https://user-images.githubusercontent.com/22895272/115062507-6c1dde80-9eb8-11eb-9544-047e78c8a431.png)

**Comment by adamjarling** [comment]
Searching the React Icons package, these icons are the closest I can find to the mockup.  https://react-icons.github.io/react-icons/search?q=circle  

Will they do?

![image](https://user-images.githubusercontent.com/3020266/115115915-95904600-9f5c-11eb-829b-575d2c884416.png)

**Comment by jessvu** [comment]
@adamjarling could I give you custom icons? I think that if we only have shapes that have no fill, we should reflect that. If so, would an SVG work? I would only be making the highlighter and shape icon. Otherwise, these should work.

**Comment by adamjarling** [comment]
Mmmmm, if you want yea you can send me SVG icons (for any of the Toolbar icons I suppose), and I'll see if I can integrate it with how the existing buttons are set up?

**Comment by adamjarling** [comment]
https://files.slack.com/files-pri/T01FY6ZS1MM-F01V671NE57/download/shapes.svg

https://files.slack.com/files-pri/T01FY6ZS1MM-F01UTJD5ZQA/download/highlighter.svg

**Comment by adamjarling** [comment]
Jess sent me the icons and I have them.   Moving this issue back to "To Do"

**Comment by jaimemears** [comment]
closing this issue. the icons are satisfactroy for mvp
