### ISSUE TITLE
Quick questions stamp

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#88]
Quick question stamps are available seperately in the toolbar at the top.  We need an icon for this and the stamps

**Comment by adamjarling** [comment]
@CourtneyMcClellan @jessvu Possible to get a visual of what this will look like?

**Comment by CourtneyMcClellan** [comment]
Yes, Jess is working on the interface, I am working on the stamps. The
stamps should look something like this, and function exactly like the
stamps, but just have its own different icon.

**Comment by jessvu** [comment]
![image](https://user-images.githubusercontent.com/32075716/115796158-55d3bf00-a39f-11eb-8e8a-498ae60fd2c7.png)
this is annotated in Figma

**Comment by CourtneyMcClellan** [comment]
Olivia is working on these and will post this weekend (4/24/21). If there are specific formatting concerns (SVG vs PNG) and labeling colors (I ask because we went back and forth on this last time and I want to make it as easy as possible) please let us know.

**Comment by jessvu** [comment]
@CourtneyMcClellan my only suggestion is to be mindful of color contrast to ensure that the questions are readable. If you are putting any text against a white background, I would use pink or navy colored text.

**Comment by adamjarling** [comment]
Ok, a few questions on my end...

- Will the speech bubble only be one color, or should the speech bubble respect active color (like regular Stamp)?
- Is the dark bubble background in which text rests (referring to image above), transparent, or does this need to be black?

I believe the most flexible implementation of this would be:

- Question text is part of the speech bubble image
- The speech bubble image is a single color (black) transparent SVG file (like this:  https://github.com/adamjarling/loc-speculative-annotations/blob/main/src/images/stamps/stamp10.svg)

Maybe we do a quick prototype with one transparent SVG speech bubble file to see how it plays out?

**Comment by CourtneyMcClellan** [comment]
Ok, a few questions on my end...

   - Will the speech bubble only be one color, or should the speech bubble
   respect active color (like regular Stamp)? Yes, one color
   - Is the dark bubble background in which text rests (referring to image
   above), transparent, or does this need to be black? We can choose
   bubbles that are solid if that would be easier. Would that make things
   easier, Adam?

I believe the most flexible implementation of this would be:

   - Question text is part of the speech bubble image Will do
   - The speech bubble image is a single color (black) transparent SVG file
   (like this:
   https://github.com/adamjarling/loc-speculative-annotations/blob/main/src/images/stamps/stamp10.svg
   )

Maybe we do a quick prototype with one transparent SVG speech bubble file
to see how it plays out?

They won't be transparent


I'm CCing Olivia on this since she is working on it today. Olivia, feel
free to throw out questions. All bubbles will be the same color and stick
to ones that don't have a clear center if aAdam prefers it.

**Comment by adamjarling** [comment]
Great, so if the speech bubble files are just one color (for example blue), and won't change colors based on active color, then this makes things much easier.  

Olivia, I think creating these speech bubble images as SVG files will work out best.  If you want to prep a sample image or 2, I can plug it in and make sure all works as expected.

**Comment by CourtneyMcClellan** [comment]
@adamjarling A quick question test stamp: https://drive.google.com/drive/folders/1_-63lFjra391bBAVWYHCnx2ES11u3bNT?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan I'm having problems opening that file in the app, and even in Adobe Illustrator.  

![image](https://user-images.githubusercontent.com/3020266/116240831-e3aa0400-a729-11eb-8d99-7c648025019c.png)

**Comment by adamjarling** [comment]
Just pushed up placeholder stamp artwork, but the UX should be mostly in place.

![image](https://user-images.githubusercontent.com/3020266/116249359-5ae39600-a732-11eb-9736-14a25d5e6caa.png)

**Comment by CourtneyMcClellan** [comment]
Great!

**Comment by CourtneyMcClellan** [comment]
Olivia updated the files, there is a new SVG as well as a PNG. Let me know if either work

https://drive.google.com/drive/folders/1_-63lFjra391bBAVWYHCnx2ES11u3bNT?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan Here's the error I'm still getting on the SVG file.  I think it's how she's exporting the file.  There should be an option in Illustrator to like trace the paths, and then you'd just export the selected paths.... something like that.

![image](https://user-images.githubusercontent.com/3020266/116294350-7d3ed900-a75d-11eb-9064-52a2e74693dd.png)

The PNG file might work too.  I can try and plug that in later this afternoon and will report back.

**Comment by CourtneyMcClellan** [comment]
https://drive.google.com/drive/folders/1_-63lFjra391bBAVWYHCnx2ES11u3bNT?usp=sharing

@adamjarling Olivia has updated the files. I am able to see the SVG files that are titled embedded. Can you access them? If they look good, I will have her upload the rest.

**Comment by adamjarling** [comment]
Yea, looking good here.  

![image](https://user-images.githubusercontent.com/3020266/116414582-32c16900-a7fe-11eb-9712-73ad6a0635ef.png)

**Comment by CourtneyMcClellan** [comment]
quick question stamps to be uploaded: https://drive.google.com/drive/folders/13JMfUgzrdoIbpXNWzCcoqwr16ulQM7XD?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan There's something a little off on the latest SVG files pushed up.   I'll check and see if using PNG files is possible instead of SVG if they continue to be troublesome.

![image](https://user-images.githubusercontent.com/3020266/117653405-f7a62a80-b159-11eb-94bd-3eb8fb6a110d.png)

![image](https://user-images.githubusercontent.com/3020266/117653576-2e7c4080-b15a-11eb-9f17-0cf01ee15661.png)

**Comment by adamjarling** [comment]
Hey @CourtneyMcClellan So in playing around with this, seems PNG files might be a more straightforward solution at this point.  I'm testing with a sample PNG file now you previously posted (`stamps-02.png`), and everything seems to work.  Note we won't be able to adjust the fill color (ie. from light blue to any currently selected color in the app), but that doesn't seem to be a current requirement anyhow.

![image](https://user-images.githubusercontent.com/3020266/117655937-51f4ba80-b15d-11eb-9e49-82e4c5ad8e1e.png)

![image](https://user-images.githubusercontent.com/3020266/117655986-61740380-b15d-11eb-9afb-75d4ae5ebaa9.png)

**Comment by CourtneyMcClellan** [comment]
Quick Questions in PNG form: https://drive.google.com/drive/folders/1aruO7wt7Cx1hakJ5RNHDIGPJwQk2Y46y?usp=sharing

**Comment by adamjarling** [comment]
New quick question stamps pulled in as PNG files and implemented.

**Comment by CourtneyMcClellan** [comment]
@adamjarling I am having trouble using the quick questions, I can select in the panel, but then I can not get out of the selection panel and it does not drop on the canvas

**Comment by adamjarling** [comment]
@CourtneyMcClellan Ah, this is a bug that started happening when I updated the UI framework we're using 2 days ago.  I noticed the bug in Select a Work and fixed it, but will apply the same fix here and to any other modals we're using as well.  Good catch.

**Comment by adamjarling** [comment]
Now updated.

![image](https://user-images.githubusercontent.com/3020266/118824095-2d948e80-b87f-11eb-9e85-cb23db329f75.png)
