### ISSUE TITLE
Pop up message

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#89]
Courtney to supply text, then assign to Adam to add text and get rid of "accept" button. Users should just x out after reading.

**Comment by CourtneyMcClellan** [comment]
what this should look like: https://speculativeannotation.slack.com/files/U01HP96FX3J/F020Q2044PQ/screen_shot_2021-05-04_at_6.19.34_pm.png

we are still working on the text

**Comment by jaimemears** [comment]
@CourtneyMcClellan will add language for pop up window.
Can we also delete the "agree" button? Users will "x" out to close.

**Comment by CourtneyMcClellan** [comment]
Text to go in the pop up: 
https://docs.google.com/document/d/155JrSghkGU09Sw2eRCxYjkC7MzyCjSU6hA2dD71oPxo/edit?usp=sharing

delete agree button, so just x out

**Comment by CourtneyMcClellan** [comment]
Pop up window text here: https://docs.google.com/document/d/1oGNOBbs1M9N877czFDLMwLjlrp2tvg1D2FdheGCulRA/edit?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan Just requested access to the private document above.

**Comment by CourtneyMcClellan** [comment]
delete agree button

**Comment by adamjarling** [comment]
![image](https://user-images.githubusercontent.com/3020266/120108223-da95c380-c129-11eb-8c95-58d34458f9cf.png)

**Comment by CourtneyMcClellan** [comment]
This looks great!
