### ISSUE TITLE
Zoom percentage updates in UI

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#93]
![image](https://user-images.githubusercontent.com/32075716/115629410-53566400-a2d0-11eb-9912-05548f79971b.png)
Percentage of zoom should change as users' zoom in/out

**Comment by adamjarling** [comment]
Zoom in/out UI control updates are made, this is just to update the Percentage value I assume?  @jessvu

**Comment by CourtneyMcClellan** [comment]
As I currently see it I don't think the zoom percentages is a valuable to our user. Is there something I am missing @jessvu about why this would be useful?

**Comment by jessvu** [comment]
@CourtneyMcClellan totally not necessary. I was just coming from the point of view that users typically like seeing and knowing this information because it is common in comparable applications; however, I think for our audience it isn't critical to display this detail. Depending on whichever update requires the least amount of time and effort on @adamjarling 's  end, we could **1)** go back to zooming in and out with just the '+' and '-' or **2)** proceed with updating percentage value (as I don't think this would negatively affect user experience)

**Comment by CourtneyMcClellan** [comment]
Got it, thanks Jess. @adamjarling either finish this out or go back to the + and -. Do whatever is the easiest, least time consuming.

**Comment by jaimemears** [comment]
development entering final sprint - closing this ticket as not a priority for mvp.
