### ISSUE TITLE
Responsive Canvas + Download Size

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#94]
![Canvas Dimensions (1)](https://user-images.githubusercontent.com/32075716/115797517-1fe40a00-a3a2-11eb-8cd0-d6acf6b4c84a.png)

![image](https://user-images.githubusercontent.com/32075716/115798038-4bb3bf80-a3a3-11eb-9a23-122d5155f0e4.png)

If possible, I would like to set the canvas and image download size to have a 3:2 aspect ratio. The size that I have attached is 1080x720, which I think would be a good size for download. 

To keep the aspect ratio consistent and responsive across all screen sizes and, let's try to keep the canvas area 40px from the bottom of the adjustment tool bar and the buttons at the bottom.

**Comment by jessvu** [comment]
https://user-images.githubusercontent.com/32075716/117083148-0469ef00-ad12-11eb-97a1-2a7e920b7c39.mov

Elements placed on canvas should respond to users changing their window size and stay pinned to where the user originally placed them.  Additionally, elements should remain the same size on the canvas the way the image does.

Allow the canvas and image to zoom in/out together, similar to the way the adobe illustrator canvas/image work together. Currently, the zoom is only focused on the image and annotations on the canvas can get lost if users adjust their window size.

**Comment by CourtneyMcClellan** [comment]
Waiting @jaimemears @CourtneyMcClellan for logo approval from Coms

**Comment by jaimemears** [comment]
Lets limit this to just concentrating on the download size. If possible, I would like to set the canvas and image download size to have a 3:2 aspect ratio. The size that I have attached is 1080x720, which I think would be a good size for download.

**Comment by jaimemears** [comment]
Closing this ticket because we checked and the download looks good.
