### ISSUE TITLE
Canvas Design/Mockup including Logo and Reserved Space for Name

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#95]
@jessvu Please mockup the canvas to include the logo and the location of the Name, Age and Town. 
For the logo: We liked the mockup with the SA Logo and the B/W LOC logo. 
For the Name: We have decided we would like to reserve space on the canvas, which may ultimately be where the following questions are located
Name:
Age:
Town

However, this must be approved by OGC (legal). We want to reserve this space on the canvas for upcoming curator annotations. To do this, please create a white box that reserves where you want these questions to go on the canvas. We want to keep the curators from writing in the box, so please include the the text "do not write in this space" in the box. 

When the canvas mockup is complete, please share it with me. If everything looks good, I will reassign to Adam. Let me know if you have any questions!

**Comment by jessvu** [comment]
![Dark Mode](https://user-images.githubusercontent.com/32075716/115943600-d74e4e80-a47e-11eb-88c3-5e3c36c9780b.png)
![Light Mode](https://user-images.githubusercontent.com/32075716/115943601-d7e6e500-a47e-11eb-9ad2-0c1df2dc3c09.png)
Hi @CourtneyMcClellan, let me know what you think of this mockup!

**Comment by adamjarling** [comment]
Curious how this will work, and what I'll need to do here...

- Who fills out the Name/Age/Town info, curators or students (app users)?
- Do they fill this information in the app itself (like a web form)?   Or is this meant to be printed out, and they just have a space to write the information in?

**Comment by CourtneyMcClellan** [comment]
This would function like a logo on the canvas-- it would be totally
optional and require no new features. This might get bumped by legal, I am
just trying to come up with a way for people to personally account for
their annotation without any sign in measures. We have shared Jess's mock
up with comms and will share it with legal.

**Comment by CourtneyMcClellan** [comment]
For now, we are just trying to reserve the space on the canvas while
curators are annotating. Actually adding the name/age/town label will
depend on legal and comms.

**Comment by adamjarling** [comment]
Starting this issue with above designs... let me know if there are any design updates.

**Comment by CourtneyMcClellan** [comment]
Th is correct. Block off space in the upper left and bottom right as depicted in the mockups.

**Comment by adamjarling** [comment]
Now updated.  Handles for light/dark mode, and all responsive sizes....but just noticed it's not part of the download image... need to fix that up then will push to staging.

![image](https://user-images.githubusercontent.com/3020266/117982579-be0d2500-b2fb-11eb-9f5a-1edaa43418ab.png)

**Comment by adamjarling** [comment]
Just fixed and will push this morning.
