### ISSUE TITLE
Highlighter with different sizes marks

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#97]
Like the marker, the highlighter needs different size stroke marks (due to the variable sizes of LOC items). It should be like the marker. 
<img width="130" alt="Screen Shot 2021-04-27 at 8 01 10 PM" src="https://user-images.githubusercontent.com/77364108/116326853-792dae00-a793-11eb-8670-77f3c27c3e0b.png">

**Comment by adamjarling** [comment]
As part of the updates for this ticket, I refactored the Adjustment bar options to be part of their own data provider.  Reduced code duplication, and kind of centralizes the logic.  

![image](https://user-images.githubusercontent.com/3020266/116817598-cbbcf080-ab2c-11eb-8619-c86acac8cd79.png)

**Comment by CourtneyMcClellan** [comment]
This looks great, thanks Adam!
