### ISSUE TITLE
canvas color change in light mode

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#99]
Canvas color needs to be change in light mode. Jess will share colors and mockups.

**Comment by jessvu** [comment]
![image](https://user-images.githubusercontent.com/32075716/116837141-3440b780-ab97-11eb-977e-236a078fad60.png)
Light-mode color palette. Adam, I tagged you in some comments for this.

**Comment by jaimemears** [comment]
development entering final sprint - closing this ticket as not a priority for mvp.
